### PR TITLE
fix(tm2/pkg/bft,os,p2p): close leaking resources

### LINKED ISSUE #3029: tm2/pkg/os: WriteFileAtomic leaks file
https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/tm2/pkg/os/tempfile.go#L110-L112 leak the created file

## Suggested remedy
Please use a defer and just check if f != nil so
```go
defer func() {
       if f != nil {
             f.Close()
             os.Remove(f.Name())
       }
}()
```

Kindly cc-ing @jaekwon

### LINKED ISSUE #3030: tm2/pkg/p2p: *MultiplexTransport.Listen leaks net.Listener on port integerization error
https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/tm2/pkg/p2p/transport.go#L248-L251 leaks the allocation listener from https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/tm2/pkg/p2p/transport.go#L240-L261

## Remedy
Please invoke ln.Close() or please use Go's named returns to help you unconditionally errors so

```go
func (mt *MultiplexTransport) Listen(addr NetAddress) (rerr error) { 
 	ln, err := net.Listen("tcp", addr.DialString()) 
 	if err != nil { 
 		return err
        }
        defer func() {
                 if rerr != nil {
                       ln.Close()
                 }
        }()
```

### LINKED ISSUE #3031: tm2/pkg/bft/privval: NewSignerListener leaks listener in case it can't recognize the protocol yet it was validly bound to
https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/tm2/pkg/bft/privval/utils.go#L42 is the route where this code leaks a listener that was validly bound to in

https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/tm2/pkg/bft/privval/utils.go#L32-L35

### PR DESCRIPTION
**Pull request by odeke-em**
This change closes some leaking resources that were identified in a preliminary code read.

Fixes #3029
Fixes #3030
Fixes #3031

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)
- [ ] The pull request description provides enough details


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: odeke-em/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

<details><summary>The pull request description provides enough details</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 Not (🔴 Pull request author is a member of the team: core-contributors)
    └── 🟢 Not (🔴 Pull request author is user: dependabot[bot])

```
### Can be checked by
 - team core-contributors

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

File: tm2/pkg/bft/privval/utils.go [hunk 1]
```diff
@@ -25,14 +25,21 @@ func IsConnTimeout(err error) bool {
...
 	protocol, address := osm.ProtocolAndAddress(listenAddr)
 	ln, err := net.Listen(protocol, address)
 	if err != nil {
 		return nil, err
 	}
+
+	defer func() {
+		if rerr != nil {
+			ln.Close()
+		}
```
Comment (thehowl) [inline tm2/pkg/bft/privval/utils.go:40]: We shouldn't close this listener, otherwise the privval signer doesn't work

File: tm2/pkg/os/tempfile.go [hunk 2]
```diff
@@ -107,14 +107,19 @@ func WriteFileAtomic(filename string, data []byte, perm os.FileMode) (err error)
 		}
 		break
 	}
+
+	// Clean up in any case.
+	defer func() {
+		if f != nil {
```
Comment (thehowl) [inline tm2/pkg/os/tempfile.go:113]: f cannot be nil at this point

File: tm2/pkg/p2p/transport.go [hunk 3]
```diff
@@ -147,13 +147,19 @@ func (mt *MultiplexTransport) Close() error {
...
-func (mt *MultiplexTransport) Listen(addr types.NetAddress) error {
+func (mt *MultiplexTransport) Listen(addr types.NetAddress) (rerr error) {
 	// Reserve a port, and start listening
 	ln, err := net.Listen("tcp", addr.DialString())
 	if err != nil {
 		return fmt.Errorf("unable to listen on address, %w", err)
 	}
 
+	defer func() {
+		if rerr != nil {
```
Comment (thehowl) [inline tm2/pkg/p2p/transport.go:158]: We shouldn't close the listener here, we should return the listener to queue it for closing, as we do for `bft.Node.rpcListeners` (I think you can re-use that one and rename the field to `listeners`)

File: tm2/pkg/bft/privval/utils.go (hunk 1 above)
Comment (odeke-em) [reply tm2/pkg/bft/privval/utils.go:40]: if the returned error is non-nil, prival signer wouldn't be working. This issues named returns in Go

File: tm2/pkg/os/tempfile.go (hunk 2 above)
Comment (odeke-em) [reply tm2/pkg/os/tempfile.go:113]: It could be if `for ; i < atomicWriteFileMaxNumWriteAttempts; i++ {` ended without getting back a valid file.

File: tm2/pkg/p2p/transport.go (hunk 3 above)
Comment (odeke-em) [reply tm2/pkg/p2p/transport.go:158]: If the named return was non-nil, we definitely should be closing it, for example if `addr.Port == 0` failed to get a TCP address. The protection using the non-nil named return error ensures that we don't leak after returning.

File: tm2/pkg/bft/privval/utils.go (hunk 1 above)
Comment (thehowl) [reply tm2/pkg/bft/privval/utils.go:40]: `rerr` is never used aside from this function

File: tm2/pkg/os/tempfile.go (hunk 2 above)
Comment (thehowl) [reply tm2/pkg/os/tempfile.go:113]: No, because we check for `err != nil`, so at this stage `err == nil` so there must be a file.

File: tm2/pkg/bft/privval/utils.go (hunk 1 above)
Comment (thehowl) [reply tm2/pkg/bft/privval/utils.go:40]: I get it now

File: tm2/pkg/os/tempfile.go (hunk 2 above)
Comment (odeke-em) [reply tm2/pkg/os/tempfile.go:113]: True true, let me update it and thank you for the discourse.

Comment (odeke-em) [reply tm2/pkg/os/tempfile.go]: Done, thanks!

**Review by thehowl — APPROVED** [review]
