### PR TITLE
fix(contribs/gnodev/pkg/emitter): use html/template not text/template for HTML generation

### LINKED ISSUE #3544: contribs/gnodev/pkg/emitter: use html/template not text/template to avoid any HTML serving issues or future unescaped XSS attacks: minor
**_This is a currently minor issue_** given that the code inside middleware.go is not attacker controlled but really when starting up a server
https://github.com/gnolang/gno/blob/d2813f87533d69409201c2ee8e87c9bcff6c1719/contribs/gnodev/pkg/emitter/middleware.go#L24
https://github.com/gnolang/gno/blob/d2813f87533d69409201c2ee8e87c9bcff6c1719/contribs/gnodev/pkg/emitter/middleware.go#L86-L89

but it is best practice to using html/template not text/template for any HTML related code. Cross site scripting (XSS) attacks occur when injected code is not correctly escaped and I gave a proof of concept for the dangers of using text/template instead of html/template at https://cyber.orijtech.com/advisory/go-xss-concat-text-template

## Exhibit
If an attacker ever got a hold of .RemoteAddr before it was generated or if the scripts evolved to later allow user input here is an exhibit of how text/template can go awry https://go.dev/play/p/dTAacWXE9uC

```go
package main

import (
	htmltmpl "html/template"
	"os"
	texttmpl "text/template"
)

var naiveTmpl = texttmpl.Must(texttmpl.New("reloadscript").Parse("const ws = new WebSocket('ws://{{- .Remote -}}');"))
var goodTmpl = htmltmpl.Must(htmltmpl.New("reloadscript").Parse("const ws = new WebSocket('ws://{{- .Remote -}}');"))

func main() {
	m := map[string]string{
		"Remote": `localhost:9999');alert('pwned`,
	}

	_ = naiveTmpl.Execute(os.Stdout, m)
	println("")
	_ = goodTmpl.Execute(os.Stdout, m)
}
```

which when ran produces

```shell
const ws = new WebSocket('ws://localhost:9999');alert('pwned');
const ws = new WebSocket('ws://localhost:9999&#39;);alert(&#39;pwned');
```

of which the first one uses text/template and will get your pwned as I can now inject arbitrary code and as a proof of concept will pop up an alert telling you `pwned` but the imagination can go wild with what you could do

but the html/template code rightfully caught the problem and produced
```
const ws = new WebSocket('ws://localhost:9999&#39;);alert(&#39;pwned');
```
which will fail to connect entirely.

### PR DESCRIPTION
**Pull request by odeke-em**
This change uses html/template instead of text/template for HTML generation and also locks in tests to detect such subtle regressions and thus help prevent future cross-side scripting (XSS) attacks if later the scripts evolve and take in user input.

Fixes #3544

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)
- [ ] The pull request description provides enough details


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: odeke-em/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

<details><summary>The pull request description provides enough details</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 Not (🔴 Pull request author is a member of the team: core-contributors)
    └── 🟢 Not (🔴 Pull request author is user: dependabot[bot])

```
### Can be checked by
 - team core-contributors

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

File: contribs/gnodev/pkg/emitter/middleware_test.go [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+			mdw := NewMiddleware(tt.remote, http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
+				rw.Header().Set("Content-Type", "text/html")
+				fmt.Fprintf(rw, "<body></body>")
+			}))
+			rec.Header().Set("Content-Type", "text/html")
+			req := httptest.NewRequest("GET", "https://gno.land/example", nil)
+			mdw.ServeHTTP(rec, req)
+
+			targets := reWebsocket.FindAllString(rec.Body.String(), -1)
+			if len(targets) == 0 {
```
Comment (thehowl) [inline contribs/gnodev/pkg/emitter/middleware_test.go:38]: Can you not use `assert` like in most other tests, which also handles diff'ing when necessary?

**Review by thehowl — APPROVED** [review]
Please address the comment and any other CI errors, and we should be good to go. Thanks!

File: contribs/gnodev/pkg/emitter/middleware_test.go (hunk 1 above)
Comment (odeke-em) [reply contribs/gnodev/pkg/emitter/middleware_test.go]: It seemed easier and nicer to use the diff-ing form google/go-cmp/cmp, but sure I've made the update to use require. Thank you and take a look.

**Comment by odeke-em** [comment]
Done and thank you @thehowl

**Review by thehowl — APPROVED** [review]

**Comment by kristovatlas** [comment]
Thank you for the contribution.
