### PR TITLE
fix:  unify the precompile output to make it easier to parse and read. 

### LINKED ISSUE #1636: Make the output of `gno precompile` more parseable
## Description

The current output of `gno precompile -gobuild` is hard to parse because it mixes 3 kinds of errors, with different format:

1) errors from `ast.Parse` the gno file content:
```
<file.gno>: precompile: parse: <file.gno>:<line>:<col>: <error>
```

Example: 
`gnovm/tests/backup/bad0.gno: precompile: parse: gnovm/tests/backup/bad0.gno:1:1: expected 'package', found println`

2) errors from `precompileAst` function, which basically verifies that all import are whitelisted:
```
<file.gno>: precompile: <error>
```

Examples:
`import "<pkg>" is not in the white list`
`failed to replace the <pkg> package with <?>`

3) errors from the `go build -v -tags=gno` command:
```
<file.gno.gen.go>:<line>:<col>: <error>
```

Example:
`./gnotest.gno.gen.go:9:2: undefined: Y`

## Improvement

To make it easier for tools like `gnols` to parse the output, all errors should have the same format, and should only output errors for `gno` files (and not `.gno.gen.go` files like in 3).

I think the best format should be something as simple as 3, but for gno file only:

```
<file.gno>:<line>:<col>: <error>
```

### PR DESCRIPTION
**Pull request by tbruyelle**
Fix #1636 

Under the hood, use `scanner.ErrorList` from the stdlib all the way to store all errors with the filename and the position in the file. Note that kind of error is already returned by `parser.ParserFile`.

For the `go build` output, instead of printing it like it is, parse it and shift it to represent the related gno file.

Run the tests:
```
$ go test ./gnovm/cmd/gno -v -run Test_ScriptsPrecompile
```

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

File: gnovm/pkg/gnolang/precompile.go [hunk 1]
```diff
@@ -161,18 +162,19 @@ func Precompile(source string, tags string, filename string) (*precompileResult,
...
 	}
-	_, err = out.WriteString(header)
+	var out bytes.Buffer
+	out.WriteString(header)
+	err = format.Node(&out, fset, transformed)
 	if err != nil {
-		return nil, fmt.Errorf("write to buffer: %w", err)
+		return nil, fmt.Errorf("format.Node: %w", err)
 	}
-	err = format.Node(&out, fset, transformed)
```
Comment (thehowl) [inline gnovm/pkg/gnolang/precompile.go:175]: can't believe this error was swallowed :facepalm:

**Review by thehowl — APPROVED** [review]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by thehowl** [comment]
Tagging @gfanton for second review/merge as he's worked on gno lint too

File: gnovm/pkg/gnolang/precompile.go [hunk 2]
```diff
@@ -246,16 +248,53 @@ func PrecompileBuildPackage(fileOrPkg string, goBinary string) error {
...
+		msg := match[4]
+		errList.Add(token.Position{
+			// Remove .gen.go extension, we want to target the gno file
+			Filename: strings.TrimSuffix(filename, ".gen.go"),
+			// Shift the 4 lines header added in *.gen.go files.
+			// NOTE(tb): the 4 lines shift below assumes there's always a //go:build
+			// directive. But the tags are optional in the Precompile() function
+			// so that leaves some doubts... We might want something more reliable than
+			// constants to shift lines.
+			Line:   line - 4,
```
Comment (deelawn) [inline gnovm/pkg/gnolang/precompile.go:289]: I'm unfamiliar with how this works.  Why does it get shifted by four lines?

Comment (thehowl) [reply gnovm/pkg/gnolang/precompile.go:289]: @deelawn https://github.com/gnolang/gno/pull/1670/files#diff-69e5bb26203ac2cfe8e34898c91adf9eca6924c6effdafb116bc4d02e9ccd3e5R168-R171

**Review by deelawn — APPROVED** [review]

File: gnovm/cmd/gno/precompile.go [hunk 3]
```diff
@@ -132,41 +134,44 @@ func execPrecompile(cfg *precompileCfg, args []string, io commands.IO) error {
 	}
 
 	opts := newPrecompileOptions(cfg)
-	errCount := 0
+	var errlist scanner.ErrorList
 	for _, filepath := range paths {
-		err = precompileFile(filepath, opts)
+		err := precompileFile(filepath, opts)
```
[the remark this answers is not in the document]
Comment (tbruyelle) [reply gnovm/cmd/gno/precompile.go]: done 1b570f0
