### PR TITLE
fix: default untyped to uint when necessary

### LINKED ISSUE #2004: Overflow Occurs When Converting `math.MaxUint64` to Floating-Point Types
### Description

When converting `math.MaxUint64` to float32 or float64 types, an overflow occurs. I think precision loss has occured during the type conversion (not sure). Note that, It works fine with `math.MaxUint32`

```go
package main

import (
  "math"
)

func main() {
  println(float64(math.MaxUint32))         // 4.294967295e+09
  println(float64(math.MaxUint64))         // error
}

// panic: bigint overflows target kind [recovered]
        panic: main/gnovm/tests/files/a0.gno:9: bigint overflows target kind:
```

Expected Output:

```go
4.294967e+09
5.421011e-02
```

### PR DESCRIPTION
**Pull request by deelawn**
Closes #2004. This change allows for passing a value to `defaultTypeOf`. In the case where we are looking for the default value of an untyped int, it can use the value, if it exists, in order to determine whether the default type should be a signed or unsigned int.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

File: gnovm/pkg/gnolang/types.go [hunk 1]
```diff
@@ -2437,7 +2446,7 @@ func specifyType(store Store, lookup map[Name]Type, tmpl Type, spec Type, specTy
 					return // ok
 				} else {
 					if isUntyped(spec) {
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/types.go:2448]: is there any chance `spec` can be untypedBigInt ?

Comment (deelawn) [reply gnovm/pkg/gnolang/types.go:2448]: I'm not sure. Maybe. Why do you ask?

**Review by zivkovicmilos — APPROVED** [review]
Looks good 💯 

Pinging @petar-dambovaliev for a second look 🙏

**Review by petar-dambovaliev — APPROVED** [review]

**Review by ltzmaxwell — APPROVED** [review]
