### PR TITLE
fix: missing length check in value declaration

### LINKED ISSUE #2137: missing length check in value declaration
This does not compile as expected, aside from the error message, which suggests that a sanity check should be performed instead of a simple type assertion.

```go
package main

func main() {
	var a, b = 1
}

// Error:
// interface conversion: gnolang.Expr is *gnolang.ConstExpr, not *gnolang.CallExpr
```

This situation is similar in that it doesn't compile as expected, but the error message indicates that it should be checked beforehand, possibly within `predefineFileSet`, and then halted.

```go
package main

func main() {
	var a, b, c = 1, a + 1
	println(a)
	println(b)
	println(c)
}

// Error:
// main/files/value_decl1.gno:3: constant definition loop with a:
```

### PR DESCRIPTION
**Pull request by omarsy**
Closes #2137 

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

File: gnovm/pkg/gnolang/preprocess.go [hunk 1]
```diff
@@ -1857,7 +1857,10 @@ func Preprocess(store Store, ctx BlockNode, n Node) Node {
 				tvs := make([]TypedValue, numNames)
 				if numNames > 1 && len(n.Values) == 1 {
 					// special case if `var a, b, c T? = f()` form.
-					cx := n.Values[0].(*CallExpr)
+					cx, ok := n.Values[0].(*CallExpr)
+					if !ok {
+						panic("should not happen")
```
Comment (thehowl) [inline gnovm/pkg/gnolang/preprocess.go:1862]: Don't add any new "should not happen" panics, please.

**Comment by thehowl** [comment]
cc @ltzmaxwell, I don't think this is what you wanted from the issue

File: gnovm/pkg/gnolang/preprocess.go (hunk 1 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:1862]: I notice many occurrences of "should not happen" in the code. I assumed it was common practice.

Indeed, it would be beneficial to include the reasons for the errors. What do you think ?

Comment (thehowl) [reply gnovm/pkg/gnolang/preprocess.go:1862]: Yeah, I'm pushing everyone working on the VM to stop adding these. They are a favourite of jae, but really the amount of times that I've had a "should not happen" panic shown in my face goes to show how much these should be avoided.

Comment (thehowl) [reply gnovm/pkg/gnolang/preprocess.go:1862]: Please make this error more descriptive; if you find others you want to improve, PRs are welcome

File: gnovm/tests/files/var19.gno [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+func main() {
+	var a, b, c = 1, a+1
+	println(a)
+	println(b)
+	println(c)
+}
+
+// Error:
+// main/files/var19.gno:3: constant definition loop with a
```
Comment (ltzmaxwell) [inline gnovm/tests/files/var19.gno:11]: as the issue says: "xxx the error message indicates that it should be checked beforehand, possibly within predefineFileSet, and then halted."

Comment (omarsy) [reply gnovm/tests/files/var19.gno]: thx for your review. Yes my bad !
Done here: https://github.com/gnolang/gno/pull/2206/commits/bd4b92444e2494f21ab1c74c8d6b697d0ad6c755

File: gnovm/pkg/gnolang/preprocess.go (hunk 1 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: Improved the error here: https://github.com/gnolang/gno/pull/2206/commits/bd4b92444e2494f21ab1c74c8d6b697d0ad6c755

File: gnovm/tests/files/var18.gno [hunk 3]
```diff
@@ -0,0 +1,8 @@
+package main
+
+func main() {
+	var a, b = 1
+}
+
+// Error:
+// main/files/var18.gno:3: assignment mismatch: 2 variable(s) but 1 value(s)
```
Comment (omarsy) [inline gnovm/tests/files/var18.gno:8]: The line isn't good. It will be fixed at: https://github.com/gnolang/gno/pull/2221

File: gnovm/pkg/gnolang/preprocess.go [hunk 4]
```diff
@@ -3039,6 +3042,18 @@ func checkIntegerType(xt Type) {
 	}
 }
 
+func checkAssignmentMismatch(d Decl) {
+	if cd, ok := d.(*ValueDecl); ok {
+		numNames := len(cd.NameExprs)
+		numValues := len(cd.Values)
+		if numValues > 0 && numValues != numNames {
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/preprocess.go:3049]: can you also consider this case:
```go
package main

func foo() (int, bool) {
	return 1, true
}

func main() {

	var a, b = 2, foo()

	println(a, b)

}
```

**Comment by ltzmaxwell** [comment]
can you change the PR title to be more directional?

File: gnovm/pkg/gnolang/preprocess.go (hunk 4 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:3049]: This case cannot be checked here because we need to evaluate `evalStaticTypeOfRaw(store, last, cx)` to determine the number of elements that the call returns. This function requires preprocessing the call before.

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/preprocess.go:3049]: can we do it in trans_leave? (I'm not sure).

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/preprocess.go:3049]: just leave it.  I guess it probably been fixed in another PR. thank u.

Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:3057]: Don't know if it is good to do it in this PR.
But done here: https://github.com/gnolang/gno/pull/2206/commits/564735c4855b43fc9f6d7634aa7cd47904d7e6c1

Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:3057]: Added here:https://github.com/gnolang/gno/commit/f9935a8b89c4bc5dee465cdc3affa801f68eb783

But don't know if we should do it in this PR

File: gnovm/pkg/gnolang/preprocess.go [hunk 5]
```diff
@@ -3039,6 +3050,18 @@ func checkIntegerType(xt Type) {
 	}
 }
 
+func checkAssignmentMismatch(d Decl) {
+	if cd, ok := d.(*ValueDecl); ok {
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/preprocess.go:3054]: 1. can we assert this before invoke this function?
2. I prefer using a name like assertXXX instead of checkXXX, what do you think?

**Review by ltzmaxwell — APPROVED** [review]

File: gnovm/pkg/gnolang/preprocess.go (hunk 5 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:3054]: > can we assert this before invoke this function?

What do you mean here ?

> I prefer using a name like assertXXX instead of checkXXX, what do you think?

I also prefer to use assertXXX, but I noticed that in this file we are using checkXXX instead of assertXXX. I have decided to stick with checkXXX for consistency.

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/preprocess.go:3054]: I mean something like this, since we only want to check against `ValueDecl`,
```go
if cd, ok := d.(*ValueDecl); ok {
    checkAssignmentMismatch(d *ValueDecl)
    ...
}
```

or even 
```go
case *ValueDecl:
    // do check staff
```

but I think the first one is just ok.

Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: done here: https://github.com/gnolang/gno/pull/2206/commits/e45a6efc65d31a0ef5adb5b30c3e093147bdddad

File: gnovm/tests/files/var21.gno [hunk 6]
```diff
@@ -0,0 +1,17 @@
+package main
+
+func foo() (int, bool) {
+	return 1, true
+}
+
+func main() {
+	var a, b = 2, foo()
```
Comment (petar-dambovaliev) [inline gnovm/tests/files/var21.gno:8]: can you add this case
```
var a, b, c = 2, foo()
```

**Review by petar-dambovaliev — APPROVED** [review]

File: gnovm/tests/files/var21.gno (hunk 6 above)
Comment (omarsy) [reply gnovm/tests/files/var21.gno:8]: done here: https://github.com/gnolang/gno/pull/2206/commits/d8236d272f7e7a0cd136b807a2adc7de8e9ac8a0

File: gnovm/pkg/gnolang/preprocess.go [hunk 7]
```diff
@@ -3051,6 +3063,20 @@ func checkIntegerKind(xt Type) {
 	}
 }
 
+func checkAssignmentMismatch(cd *ValueDecl) {
+	var (
+		numNames  = len(cd.NameExprs)
+		numValues = len(cd.Values)
+	)
+	if numValues <= 0 || numValues == numNames {
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/preprocess.go:3071]: there's no chance numValues <= 0, right?

File: gnovm/pkg/gnolang/preprocess.go [hunk 8]
```diff
@@ -2084,6 +2088,14 @@ func Preprocess(store Store, ctx BlockNode, n Node) Node {
 				} else if len(n.Values) != 0 && numNames != len(n.Values) {
 					panic("should not happen")
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/preprocess.go:2089]: can you also modify this message as what you did above?

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/preprocess.go:2089]: and add a test like this:
```go
package main

var a, b, c = 1, 2

func main() {
}
``` 
correspondingly.

File: gnovm/pkg/gnolang/preprocess.go (hunk 7 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: Yes right we only need this `numValues == 0`

File: gnovm/pkg/gnolang/preprocess.go (hunk 8 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: should be added here: 89d1130af546002437b6ce2daa47553573bd30c8

File: gnovm/pkg/gnolang/preprocess.go (hunk 7 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: edited here: 89d1130af546002437b6ce2daa47553573bd30c8

**Comment by petar-dambovaliev** [comment]
@omarsy can you resolve the comments, if they are done so we can move forward with this PR?

**Comment by n0izn0iz** [comment]
@petar-dambovaliev

from [CONTRIBUTING.md](https://github.com/gnolang/gno/blob/master/CONTRIBUTING.md#how-do-i-submit-changes):
> The PR reviewer is in charge of resolving each conversation (hitting the Resolve Conversation button), after the PR creator implements or discusses the requested changes

File: gnovm/pkg/gnolang/preprocess.go (hunk 8 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: @ltzmaxwell  is it good for you ?

File: gnovm/pkg/gnolang/preprocess.go (hunk 7 above)
Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/preprocess.go]: `numValues == 0` when RHS is empty? that won't parse at all.

**Comment by ltzmaxwell** [comment]
LGTM

**Review by mvertes — APPROVED** [review]
Looks good to me.

File: gnovm/pkg/gnolang/preprocess.go [hunk 9]
```diff
@@ -438,8 +438,12 @@ func Preprocess(store Store, ctx BlockNode, n Node) Node {
 					// skip declarations already predefined
 					// (e.g. through recursion for a dependent)
 				} else {
+					d := n.(Decl)
+					if cd, ok := d.(*ValueDecl); ok {
+						checkAssignmentMismatch(cd)
+					}
```
Comment (thehowl) [inline gnovm/pkg/gnolang/preprocess.go:444]: This should also be applied in AssignStmt -> DEFINE, though note that there is already a check in type_check.go (see AssignStmt.AssertCompatible); so maybe merge them instead of doing the check twice.

Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:444]: Sorry, I didn't understand. In my case, I think I am  checking the ValueDecl (when using var) then in  the type_check.go we are checking the AssignStmt (when using `:=`).

Comment (thehowl) [reply gnovm/pkg/gnolang/preprocess.go:444]: yes. but since your error message is good, it should show up also when we have a mismatch with := (ie. `a, b := 1`). Currently, it doesn't show up

Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go:444]: I just managed the value declaration part for this PR.  I will handle assignment case also if you want

Comment (omarsy) [reply gnovm/pkg/gnolang/preprocess.go]: Done here: https://github.com/gnolang/gno/pull/2206/commits/3ea7a53397a861f7acb83bdc0dbcd9c10b750143

Should fix this too: https://github.com/gnolang/gno/issues/2637

File: gnovm/pkg/gnolang/type_check.go [hunk 10]
```diff
@@ -215,6 +215,70 @@ func assertAssignableTo(xt, dt Type, autoNative bool) {
...
+			return
+		case *TypeAssertExpr:
+			if numNames != 2 {
+				panic(fmt.Sprintf("assignment mismatch: %d variable(s) but %d value(s)", numNames, numValues))
+			}
+			return
+		case *IndexExpr:
+			if numNames != 2 {
+				panic(fmt.Sprintf("assignment mismatch: %d variable(s) but %d value(s)", numNames, numValues))
+			}
```
Comment (thehowl) [inline gnovm/pkg/gnolang/type_check.go:266]: Okay, maybe we should check to see what happens when we have an expression like `a, ok := s[1]`, where `s` is a string or a slice.

**Review by thehowl — APPROVED** [review]
