### PR TITLE
fix(gnovm): avoid  panic for non-constant literal composite

### LINKED ISSUE #3964: Invalid "duplicate key" panic for non-constant literal composite
The following valid Go program panics with gno:

```go
package main

import "fmt"

func main() {
    x := 1
    a := map[int]int{x: 10, 1 * x: 20} // x and 1*x denote the same key
    fmt.Println(a)
}
```

With go:

```console
$ go run sample.go
map[1:20]
```

With gno:

```console
$ gnu run sample.go
panic running expression main(): duplicate key %!s(<nil>) in map literal
[...]
```

The panic would be correct if `x` was declared as constant: `const x = 1`, but not if x is a variable. In this case the map value for key `1` should be re-assigned.

The issue occurs for all key types which admit a constant value. The problem is that the expression processing of the key does not distinguish between a constant and a variable expression.

### PR DESCRIPTION
**Pull request by mvertes**
Panic on "duplicate key" only for constant expressions, not ones involving variables. Note: this applies only to maps, as other indexes or selectors always require constants or identifiers.

Fixes #3964.

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: mvertes/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

File: gnovm/pkg/gnolang/op_expressions.go [hunk 1]
```diff
@@ -555,7 +555,7 @@ func (m *Machine) doOpMapLit() {
 			ktv := &kvs[i*2]
 			vtv := kvs[i*2+1]
 			ptr := mv.GetPointerForKey(m.Alloc, m.Store, ktv)
-			if ptr.TV.IsDefined() {
+			if ptr.TV.IsDefined() && isConst(x.Elts[i].Key) {
 				// map key has already been assigned
 				panic(fmt.Sprintf("duplicate key %s in map literal", ktv.V))
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/op_expressions.go:560]: LGTM. 👍 .
nitpick: in some cases ktv.V is nil, it can be fixed here or later.

**Review by ltzmaxwell — APPROVED** [review]

**Review by omarsy — APPROVED** [review]
LGTM. 
(Created issue https://github.com/gnolang/gno/issues/3988 to fail during preprocessing if duplicate keys exist due to constant values)

**Review by thehowl — APPROVED** [review]
