### PR TITLE
fix(tm2/gnovm): multi-msg overwrites previous event(s)

### LINKED ISSUE #2028: bug(tm2/gnovm): multi-msg call overwrites previous event
## Bug: multi-msg call overwrites previous event
related pr #1653

### Description

event gets overwrite in multi-msg transaction call

### Steps to reproduce

---
deploy first contract
```go
package event2

import (
	"std"
)

func Hello() {
	inner()
	std.Emit("t", "k", "v")
}

func inner() {
	std.Emit("t", "k", "v")
}

```

--- 
deploy second contract
```go
package event

import (
	"std"

	e2 "gno.land/r/demo/event2"
)

func Hello() {
	inner()
	std.Emit("t", "k", "v")
}

func inner() {
	e2.Hello()
	std.Emit("t", "k", "v")
}

func Other() {
	std.Emit("other", "k", "v")
}
```

call with multi-msg like below (with adena)
```javascript
await adena.DoContract({
    messages: [{
        "type": "/vm.m_call",
        "value": {
          "caller": "g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5",
          "send": "",
          "pkg_path": "gno.land/r/demo/event",
          "func": "Hello",
          "args": []
        }
      },{
        "type": "/vm.m_call",
        "value": {
          "caller": "g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5",
          "send": "",
          "pkg_path": "gno.land/r/demo/event",
          "func": "Other",
          "args": []
        }
      }],
    gasFee: 1, 
    gasWanted: 2000000
  });
```

### Expected behaviour

should print each function's events

### Actual behaviour

```json
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "height": "43",
    "results": {
      "deliver_tx": [
        {
          "ResponseBase": {
            "Error": null,
            "Data": null,
            "Events": [
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "other",
                "func": "Other",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              },
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "other",
                "func": "Other",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              }
            ],
            "Log": "msg:0,success:true,log:,events:[]\nmsg:1,success:true,log:,events:[]",
            "Info": ""
          },
          "GasWanted": "2000000",
          "GasUsed": "270168"
        }
      ],
      "end_block": {
        "ResponseBase": {
          "Error": null,
          "Data": null,
          "Events": null,
          "Log": "",
          "Info": ""
        },
        "ValidatorUpdates": null,
        "ConsensusParams": null,
        "Events": null
      },
      "begin_block": {
        "ResponseBase": {
          "Error": null,
          "Data": null,
          "Events": null,
          "Log": "",
          "Info": ""
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by r3v4s**
Closes #2028 

root cause: `defer` was used inside of loop that handles multi-msg. It was causing vm to use only last appended event value 

---
## AS-IS
```json
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "height": "43",
    "results": {
      "deliver_tx": [
        {
          "ResponseBase": {
            "Error": null,
            "Data": null,
            "Events": [
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "other",
                "func": "Other",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              },
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "other",
                "func": "Other",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              }
            ],
            "Log": "msg:0,success:true,log:,events:[]\nmsg:1,success:true,log:,events:[]",
            "Info": ""
          },
          "GasWanted": "2000000",
          "GasUsed": "270168"
        }
      ],
      "end_block": {
        "ResponseBase": {
          "Error": null,
          "Data": null,
          "Events": null,
          "Log": "",
          "Info": ""
        },
        "ValidatorUpdates": null,
        "ConsensusParams": null,
        "Events": null
      },
      "begin_block": {
        "ResponseBase": {
          "Error": null,
          "Data": null,
          "Events": null,
          "Log": "",
          "Info": ""
        }
      }
    }
  }
}
```
---

## TO-BE (in this PR)
```json
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "height": "6",
    "results": {
      "deliver_tx": [
        {
          "ResponseBase": {
            "Error": null,
            "Data": null,
            "Events": [
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event2",
                "type": "t",
                "func": "inner",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              },
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event2",
                "type": "t",
                "func": "Hello",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              },
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "t",
                "func": "inner",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              },
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "t",
                "func": "Hello",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              },
              {
                "@type": "/tm.gnoEvent",
                "pkg_path": "gno.land/r/demo/event",
                "type": "other",
                "func": "Other",
                "attrs": [
                  {
                    "key": "k",
                    "value": "v"
                  }
                ]
              }
            ],
            "Log": "msg:0,success:true,log:,events:[{gno.land/r/demo/event2 t inner [{k v}] \u003cnil\u003e} {gno.land/r/demo/event2 t Hello [{k v}] \u003cnil\u003e} {gno.land/r/demo/event t inner [{k v}] \u003cnil\u003e} {gno.land/r/demo/event t Hello [{k v}] \u003cnil\u003e}]\nmsg:1,success:true,log:,events:[{gno.land/r/demo/event2 t inner [{k v}] \u003cnil\u003e} {gno.land/r/demo/event2 t Hello [{k v}] \u003cnil\u003e} {gno.land/r/demo/event t inner [{k v}] \u003cnil\u003e} {gno.land/r/demo/event t Hello [{k v}] \u003cnil\u003e} {gno.land/r/demo/event other Other [{k v}] \u003cnil\u003e}]",
            "Info": ""
          },
          "GasWanted": "2000000",
          "GasUsed": "270168"
        }
      ],
      "end_block": {
        "ResponseBase": {
          "Error": null,
          "Data": null,
          "Events": null,
          "Log": "",
          "Info": ""
        },
        "ValidatorUpdates": null,
        "ConsensusParams": null,
        "Events": null
      },
      "begin_block": {
        "ResponseBase": {
          "Error": null,
          "Data": null,
          "Events": null,
          "Log": "",
          "Info": ""
        }
      }
    }
  }
}
```

FYI, unable to provide any test cases(unit test, integration test or txtar) due to lack of multi-msg testing.

---

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by leohhhn** [comment]
@r3v4s 

Can you provide the code you used to get the block output from the PR description?

**Comment by r3v4s** [comment]
> @r3v4s
> 
> Can you provide the code you used to get the block output from the PR description?

oh result is actual chain result (:26657/block_results)

File: tm2/pkg/sdk/baseapp.go [hunk 1]
```diff
@@ -652,11 +652,9 @@ func (app *BaseApp) runMsgs(ctx Context, msgs []Msg, mode RunTxMode) (result Res
 		// Each message result's Data must be length prefixed in order to separate
 		// each result.
 		data = append(data, msgResult.Data...)
-		events = append(events, msgResult.Events...)
```
Comment (moul) [inline tm2/pkg/sdk/baseapp.go:655]: you shouldn't remove this from the slice `msgResult.Events...`

File: tm2/pkg/sdk/baseapp.go [hunk 2]
```diff
@@ -652,11 +652,9 @@ func (app *BaseApp) runMsgs(ctx Context, msgs []Msg, mode RunTxMode) (result Res
...
-		defer func() {
```
Comment (moul) [inline tm2/pkg/sdk/baseapp.go:656]: I think it was a good approach, but you likely shadowed a variable or overrode one that was already in use. It appears more like a variable usage race.

File: tm2/pkg/sdk/baseapp.go (hunk 1 above)
Comment (r3v4s) [reply tm2/pkg/sdk/baseapp.go:655]: 102c0d663cbf4d37c5a0ba7e1bd6966e8cad7b2a

File: tm2/pkg/sdk/baseapp.go (hunk 2 above)
Comment (r3v4s) [reply tm2/pkg/sdk/baseapp.go:656]: 2ace123c597ad4637fed9a1da7d101e1802b1b09

event from @notJoon #1653 is in context level unlike `msgResult.event` is defined for each msgs. So based on my understanding we don't need handle this in loop.

**Review by zivkovicmilos — APPROVED** [review]
Looks good 💯

**Comment by ajnavarro** [comment]
Could you add a test verifying the behavior? Thanks!

**Review by ajnavarro — APPROVED** [review]

File: gno.land/pkg/gnoclient/integration_test.go [hunk 3]
```diff
@@ -113,6 +114,64 @@ func TestCallMultiple_Integration(t *testing.T) {
...
+
+	// Execute call
+	res, err := client.Call(baseCfg, msg1, msg2)
+	assert.Nil(t, err)
+
+	// check response from block_results to get event
+	blockRes, err := client.BlockResult(res.Height)
+	assert.Nil(t, err)
+
+	// XXX: better comparison ?
```
Comment (moul) [inline gno.land/pkg/gnoclient/integration_test.go:167]: Please ensure that you have exactly two events.

File: gno.land/pkg/gnoclient/integration_test.go [hunk 4]
```diff
@@ -113,6 +114,64 @@ func TestCallMultiple_Integration(t *testing.T) {
...
+		Send:     "",
+	}
+
+	// Execute call
+	res, err := client.Call(baseCfg, msg1, msg2)
+	assert.Nil(t, err)
+
+	// check response from block_results to get event
+	blockRes, err := client.BlockResult(res.Height)
+	assert.Nil(t, err)
```
Comment (moul) [inline gno.land/pkg/gnoclient/integration_test.go:165]: If I'm not mistaken, there is an assert.NoError function that provides more details if the error is not nil.

File: gno.land/pkg/gnoclient/integration_test.go (hunk 3 above)
Comment (r3v4s) [reply gno.land/pkg/gnoclient/integration_test.go:173]: 4be002898a9e9ee9f054736818b7b838ceb3ebd3

File: gno.land/pkg/gnoclient/integration_test.go (hunk 4 above)
Comment (r3v4s) [reply gno.land/pkg/gnoclient/integration_test.go:165]: 4be002898a9e9ee9f054736818b7b838ceb3ebd3

**Review by moul — APPROVED** [review]

File: gno.land/pkg/gnoclient/integration_test.go [hunk 5]
```diff
@@ -113,6 +114,70 @@ func TestCallMultiple_Integration(t *testing.T) {
 	assert.Equal(t, expected, got)
 }
 
+func TestCallMultipleEvent_Integration(t *testing.T) {
```
Comment (thehowl) [inline gno.land/pkg/gnoclient/integration_test.go:117]: No, I'm sorry. This is not testing gnoclient, it is testing the chain. You should write a `txtar` test where you run gnokey with a transaction generated by combining two transactions, ie. running `sign` and `broadcast` from an already generated transaction result.

This may sound nitpicky, but honestly I already hate that we have txtar tests because we don't have a system to properly unit-tests things on the TM2 side. We will not test chain behaviour with the gnoclient package. If something fails here, it should be gnoclient's fault, not the chain code (other code should scream at you when that happens).

**Review by thehowl — APPROVED** [review]
okay, I'm very confused by the baseapp code deleted but I think that if it was guarding against some important scenario then it should have had a test case. please fix the test and we're good to go.

File: gno.land/pkg/gnoclient/integration_test.go (hunk 5 above)
Comment (r3v4s) [reply gno.land/pkg/gnoclient/integration_test.go:117]: AFAIK, gnokey in txtar doesn't support sign(not sure about broadcast).
Is there way around to test it?
