### PR TITLE
fix(bft): correctly drain channels events

### LINKED ISSUE #1320: make `make _test.pkg.bft` consistent, especially on CI (`tm2/test`)
This is the test with the highest flappiness/flakiness.

Related with #202

### PR DESCRIPTION
**Pull request by gfanton**
addresses #1320 

This PR does two things:
- It prevents deadlocks in state_test by triggering a panic if `GetRoundState` becomes blocked. In the event of any panic, it will attempt to drain all relevant channels to identify which events have not been drained.
- It fixes tests that have been failing randomly on the CI.

---

for now, you can checkout this branch, it will fail locally (using @jaekwon [trick](https://github.com/gnolang/gno/issues/1320#issuecomment-1881561931))

There are still some tests that I was unable to resolve. I have marked these with `// XXX(FIXME)` in `tm2/pkg/bft/consensus/state_test.go`:
- TestStateFullRound1
- TestWaitingTimeoutProposeOnNewRound
- TestStateEnterProposeYesPrivValidator
- TestStartNextHeightCorrectly

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by jaekwon** [comment]
Thank you for doing this work.

**Comment by gfanton** [comment]
@moul 

Current state is:
- The PR causes the BFT test to fail early and shows the drained channel to aid debugging.
-  I've fixed some tests by rearranging the event order.
- Unfotunatly, rearranging event consumption will not resolve the last 3 failing test. Or at last i wasn't able to do so.
- I still believe the root issue lies not in the event system (even if there are rooms for improvement), but in how we test event ordering.

What we can do:
-  The core problem, to me, is that in an event bus system, a subscription is meant to be consumed. The test is actually leaving subscriptions on hold, which ultimately leads to the test getting stuck. This is especially true for a system that is meant to have no buffer size for sync reasons.
  - I still believe that using a single routine to queue events inside the tests can be a good idea. Even if the routine is asynchronous, events will be stored in the queue in the correct order.
-  Another potential solution could be to make subscriptions cancelable. By doing so, we can simply cancel previously stuck subscription. However, I'm still not sure about this, as we may still encounter a problem where a necessary subscription is stuck and cannot be canceled.

**Comment by moul** [comment]
Let's talk about merging the current state to enhance global efficiency in the upcoming review meeting. We can then collaborate with @jaekwon to resolve the remaining cases.

**Comment by thehowl** [comment]
Review Meeting: @gfanton to do a cleanup / take another look, @jaekwon to review.

File: tm2/pkg/bft/consensus/state_test.go [hunk 1]
```diff
@@ -1468,7 +1495,8 @@ func TestStartNextHeightCorrectly(t *testing.T) {
 	time.Sleep(5 * time.Millisecond)
 	signAddVotes(cs1, types.PrecommitType, theBlockHash, theBlockParts, vs4)
 
-	rs = cs1.GetRoundState()
+	// XXX(FIXME): this make the test hang indefinitely
+	rs = ensureGetRoundState(cs1)
```
Comment (jaekwon) [inline tm2/pkg/bft/consensus/state_test.go:1499]: this is because there isn't a new round to get, it should still be in the same round, but the round state field has changed. We can just revert to the previous line.

File: tm2/pkg/bft/consensus/state_test.go [hunk 2]
```diff
@@ -183,13 +185,16 @@ func TestStateEnterProposeYesPrivValidator(t *testing.T) {
...
 
 	// Wait for new round so proposer is set.
 	ensureNewRound(newRoundCh, height, round)
 	ensureNewProposal(proposalCh, height, round)
 
+	// XXX(FIXME): new round loop block get round state
+
 	// Check that Proposal, ProposalBlock, ProposalBlockParts are set.
-	rs := cs.GetRoundState()
+	rs := ensureGetRoundState(cs)
```
Comment (jaekwon) [inline tm2/pkg/bft/consensus/state_test.go:197]: looks like this is failing because ensureGetRoundState() waits, and meanwhile there was another round produced.
do we need the time.Sleep(5) in ensureGetRoundState(cs)? If so it's probably masking some bug, so we should just get rid of that. And then this function will complete before the next round. 

------
FUTURE WORK:

Even with the above, it's still technically racy because we're assuming that cs.GetRoundState() will complete before the next round starts. Even for the CI this should generally hold, but it's not guaranteed. The complete solution should be to allow the consensus reactor to be given allowances of execution, so that the test can give it more allowances (of rounds, or messages to process from the WAL). This is a bit more challenging but not that much more so. We basically need to support maxSteps and make sure only this many messages from either the peerMsgQueue or internalMsgQueue (I think both, but not 100% sure) are processed in ConsensusState.receiveRoutine, and then to exit that routine once the maxSteps allowance is complete. And then in the test we need to give it more allowance, which re-starts the receiveRoutine (in a separate goroutine) with the allowed maxSteps. If we are going to do this, we should convert one or few test cases first. 

-----

For now I'm pretty sure we can just remove time.Sleep(5) in ensureGetRoundState(). Do we really need ensureGetRoundState() separate from .GetRoundState()? e.g. does it actually help with debug/trace for the developer to know what's going on? If it doesn't help, we can also revert ensureGetRoundState() to .GetRoundState() as it is simpler.

Comment (gfanton) [reply tm2/pkg/bft/consensus/state_test.go]: Thanks, @jaekwon. I wasn't sure if these tests should work without `ensureGetRoundState`. The sole purpose of `ensureGetRoundState` was to:
-  Delay the check of GetRoundState so that **the test fails locally**.
-  Add a timeout so that **the test fails early** (no need to wait 10 minutes).
The delay wasn't meant to be pushed in the first place, but it helped me test locally until all the issues were resolved. I was thinking that the tests should work with or without the delay as (as you says) it leave some tests technically racy.
But If you confirm this is sufficient for now, I am content with the current state. :)
I will cleanup the PR and it should be good for a final review

Comment (gfanton) [reply tm2/pkg/bft/consensus/state_test.go]: Regarding the "FUTURE WORK" section, I will definitely take a look to see if it cannot be a quick win.

**Comment by gfanton** [comment]
TL;DR: Reverting `ensureGetRoundState` to `GetRoundState` by eliminating the delay should resolve the last tests (even if technically they are still racy), boosting CI success rate to nearly 100%.
After merging, we should monitor ﻿`consensus/state_test.go` in future PRs to handle any remaining flaky tests.

File: tm2/pkg/bft/consensus/common_test.go [hunk 3]
```diff
@@ -762,3 +763,48 @@ func newPersistentKVStore() abci.Application {
...
+		}
+
+		for {
+			chosen, recv, recvOK := reflect.Select(cases)
+			if chosen != 0 || !recvOK {
+				break
+			}
+
+			leaks[reflect.TypeOf(recv.Interface()).String()]++
+			time.Sleep(time.Millisecond * 500)
```
Comment (zivkovicmilos) [inline tm2/pkg/bft/consensus/common_test.go:801]: I'm not sure if this is a long sleep duration. Did you try making this ex 100ms?

File: tm2/pkg/bft/consensus/common_test.go [hunk 4]
```diff
@@ -762,3 +763,48 @@ func newPersistentKVStore() abci.Application {
 func newPersistentKVStoreWithPath(dbDir string) abci.Application {
 	return kvstore.NewPersistentKVStoreApplication(dbDir)
 }
+
+// ------------------------------------
+
+func ensureDrainedChannels(t *testing.T, channels ...any) {
```
Comment (zivkovicmilos) [inline tm2/pkg/bft/consensus/common_test.go:769]: I hope I can men-in-black my brain after seeing this reflect trickery for channels

**Review by zivkovicmilos — APPROVED** [review]
You know I'm not a fan of these sorts of fixes, especially when they use the hidden jutsu of reflect :)

I think it's finally time to put the flaky CI to rest (at least most of it), so I'm willing to move on this fix 👏 

It is worth noting that we have fixed all of these issues in the libtm testing suite, so even these tests are just here temporarily

File: tm2/pkg/bft/consensus/common_test.go (hunk 4 above)
Comment (gfanton) [reply tm2/pkg/bft/consensus/common_test.go:769]: ahaha, I created this method as a general-purpose tool for debugging undrained channels to check for events that haven't been consumed yet in case of failure. It wasn't meant to be pushed initially, as it was a debug method. However, I discussed this with Jae, and we want to keep it in case of another CI failure so we have a trace for this.

File: tm2/pkg/bft/consensus/common_test.go (hunk 3 above)
Comment (gfanton) [reply tm2/pkg/bft/consensus/common_test.go:801]: This method is only triggered on panic, so it only happens on failure, see my comment bellow ;)
