### PR TITLE
fix(gnodev): skip failing tx instead of raising an error

### LINKED ISSUE #1447: contribs/gnodev: start node even if the package fails to publish
Currently, if the gnodev command fails to publish any package, Node fails to start. In my opinion, it should still start the Node even if it fails to publish the package and keep watching/monitoring the given package. It should still be able to hot reload.

Here is an example where a Realm developer will not be able to watch the Realm:

Imagine:
- I'm working on some package, `helloworld`, and it uses `p/avl`.
- Let's say there is some problem in `r/boards` (that exists in the example directory).

In the above scenario, if I run `gnodev path/to/helloworld`, it won't be able to start the Node, saying there is an error in loading `r/boards`, blah blah blah... even if `helloworld` never imports `r/boards`.

PS: Thanks @gfanton for #1386 ❤️

### PR DESCRIPTION
**Pull request by gfanton**
fix #1447

Skip failing TX instead of raising an error.
Also adjust/add some comments in dev node package for better understanding and readability 

cc @harry-hov 

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Review by deelawn — APPROVED** [review]
Makes sense to me 👍

File: contribs/gnodev/main.go [hunk 1]
```diff
@@ -128,7 +128,7 @@ func execDev(cfg *devCfg, args []string, io commands.IO) error {
 
 	// Setup Dev Node
 	// XXX: find a good way to export or display node logs
-	devNode, err := setupDevNode(ctx, rt, pkgpaths, gnoroot)
+	devNode, err := setupDevNode(ctx, rt, pkgpaths)
```
Comment (deelawn) [inline contribs/gnodev/main.go:131]: The function signature of `setupDevNode` needs to be changed as well

**Review by deelawn — CHANGES_REQUESTED** [review]

File: contribs/gnodev/main.go (hunk 1 above)
Comment (gfanton) [reply contribs/gnodev/main.go:131]: Updated, i've also added `make install.gnodev` to the CI to have a minimal build integration

**Review by deelawn — APPROVED** [review]

**Review by thehowl — COMMENTED** [review]
The changes look good so approving.

I'm wondering though: should an end-user not clearly be able to see any error publishing the specific packages they're publishing?

I get what Hariom is saying in the issue, however if I'm working on a realm and I introduce a bug, I would want `gnodev` to prominently and clearly tell me what the generated error/panic while publishing the package is.

**Review by thehowl — APPROVED** [review]

**Comment by harry-hov** [comment]
Not sure if my expectations are realistic or not, but I expect output something like:

Case 1: When `p/helloworld` does not imports `avl`  
```sh
$ ~/De/w/gno/examples ❯ gnodev gno.land/r/demo/helloworld
Node            | Listener: tcp://0.0.0.0:36657
[...]
Node            | Loading packages...
Node            | Failed to load `gno.land/p/demo/avl`...
                       - cannot use 0 (untyped int constant) as *Tree value in return statement
Node            | Successfully loaded `gno.land/r/demo/helloworld`...      
Node            | [DONE - with 1 error]
```

In this case, I can continue working on `r/helloworld` without need to worry about fixing `p/avl`

Case 1: When `p/helloworld` imports `avl`  
```sh
$ ~/De/w/gno/examples ❯ gnodev gno.land/r/demo/helloworld
Node            | Listener: tcp://0.0.0.0:36657
[...]
Node            | Loading packages...
Node            | Failed to load `gno.land/p/demo/avl`...
                       - cannot use 0 (untyped int constant) as *Tree value in return statement
Node            | Failed to load `gno.land/r/demo/helloworld`...    
                       - Missing package gno.land/p/demo/avl
Node            | [DONE - with 2 errors]
```

In this case, since i imports `p/avl` i need to fix it first before continue working on `r/helloworld`.

--- 

We should also have -verbose incase someone wants to see the detailed error msg.

**Review by harry-hov — APPROVED** [review]

File: contribs/gnodev/pkg/dev/node.go [hunk 2]
```diff
@@ -108,14 +102,16 @@ func (d *Node) GetRemoteAddress() string {
 	return d.Node.Config().RPC.ListenAddress
 }
 
+// UpdatePackages updates the package currently know packages. It will be take in consideration in the next reload of the node.
```
Comment (harry-hov) [inline contribs/gnodev/pkg/dev/node.go:105]:
```suggestion
// UpdatePackages updates the currently known packages. It will be taken into 
// consideration in the next reload of the node.
```

**Comment by gfanton** [comment]
@harry-hov @thehowl it should be possible, I have an idea on how we can implement this. but I will do this in another PR
