### PR TITLE
fix(gnovm): improve ComputeMapKey uniqueness

### LINKED ISSUE #4567: ComputeMapKey can yield the same result for different values
Something that has been bothering me for a while, but I just needed to come up with a MVP.

```go
package main

func main() {
	x := map[any]string{}
	k1 := [2]string{"hi,wor", "ld"}
	k2 := [2]string{"hi", "wor,ld"}
	x[k1] = "123"
	x[k2] = "456"
	println(x)
}

// Output:
// map{(array[("hi,wor" string),("ld" string)] [2]string):("456" string)}
```

Note the single value printed, in spite of the two keys.

ComputeMapKey yields the same value (`[2]string:[hi,wor,ld]`), so it's easy to trick.

More examples:

```go
package main

func main() {
	x := map[any]string{}
	k1 := [2]any{"hi,string:wor", "ld"}
	k2 := [2]any{"hi", "wor,string:ld"}
	x[k1] = "123"
	x[k2] = "456"
	println(x)
}
```

The easiest way is probably to make strings have a length prefix, which I think should make it impossible to make strings "escape" properly.

### PR DESCRIPTION
**Pull request by thehowl**
Fix #4567 

Create a system whereby values are len-prefixed to create unique strings for ComputeMapKey.

Please, try to consider if this can be "evaded" somehow like the previous system.

Depends on https://github.com/gnolang/gno/pull/4961

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: thehowl/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

**Comment by jaekwon** [comment]
I'll take a look end of this week ish

**Comment by jaekwon** [comment]
Taking a look today.

**Comment by jaekwon** [comment]
I recommend this from master, and your test files. I'll comment also on the files for justification.

```diff
diff --git a/gnovm/pkg/gnolang/values.go b/gnovm/pkg/gnolang/values.go
index c328e40a6..d4aa317f0 100644
--- a/gnovm/pkg/gnolang/values.go
+++ b/gnovm/pkg/gnolang/values.go
@@ -7,7 +7,6 @@ import (
 	"fmt"
 	"math/big"
 	"reflect"
-	"strconv"
 	"unsafe"
 
 	"github.com/cockroachdb/apd/v3"
@@ -1020,14 +1019,14 @@ func (tv *TypedValue) IsNilInterface() bool {
 	return false
 }
 
-func (tv *TypedValue) IsNaN() bool {
+func (tv *TypedValue) IsNaN() (isNaN bool) {
 	switch tv.T.Kind() {
 	case Float32Kind:
-		_, _, _, _, nan := softfloat.Funpack32(tv.GetFloat32())
-		return nan
+		_, _, _, _, isNaN = softfloat.Funpack32(tv.GetFloat32())
+		return isNaN
 	case Float64Kind:
-		_, _, _, _, nan := softfloat.Funpack64(tv.GetFloat64())
-		return nan
+		_, _, _, _, isNaN = softfloat.Funpack64(tv.GetFloat64())
+		return isNaN
 	default:
 		return false
 	}
@@ -1100,35 +1099,54 @@ func (tv TypedValue) unrefCopy(alloc *Allocator, store Store) (cp TypedValue) {
 
 // Returns encoded bytes for primitive values.
 // These are used for computing map keys.
-func (tv *TypedValue) PrimitiveBytes(bz []byte) []byte {
+// If NaN float32|float64 returns bz unchanged and isNaN=true.
+func (tv *TypedValue) MapKeyBytes(bz []byte) (bz2 []byte, isNaN bool) {
 	switch bt := baseOf(tv.T); bt {
 	case BoolType:
 		if tv.GetBool() {
-			return append(bz, 0x01)
+			return append(bz, 0x01), false
 		}
-		return append(bz, 0x00)
+		return append(bz, 0x00), false
 	case StringType:
-		return append(bz, tv.GetString()...)
+		return append(bz, tv.GetString()...), false
 	case Int8Type:
-		return append(bz, uint8(tv.GetInt8()))
+		return append(bz, uint8(tv.GetInt8())), false
 	case Int16Type:
-		return binary.LittleEndian.AppendUint16(bz, uint16(tv.GetInt16()))
+		return binary.LittleEndian.AppendUint16(bz, uint16(tv.GetInt16())), false
 	case Int32Type:
-		return binary.LittleEndian.AppendUint32(bz, uint32(tv.GetInt32()))
+		return binary.LittleEndian.AppendUint32(bz, uint32(tv.GetInt32())), false
 	case IntType, Int64Type:
-		return binary.LittleEndian.AppendUint64(bz, uint64(tv.GetInt()))
+		return binary.LittleEndian.AppendUint64(bz, uint64(tv.GetInt())), false
 	case Uint8Type:
-		return append(bz, tv.GetUint8())
+		return append(bz, tv.GetUint8()), false
 	case Uint16Type:
-		return binary.LittleEndian.AppendUint16(bz, tv.GetUint16())
+		return binary.LittleEndian.AppendUint16(bz, tv.GetUint16()), false
 	case Uint32Type:
-		return binary.LittleEndian.AppendUint32(bz, tv.GetUint32())
+		return binary.LittleEndian.AppendUint32(bz, tv.GetUint32()), false
 	case UintType, Uint64Type:
-		return binary.LittleEndian.AppendUint64(bz, tv.GetUint())
+		return binary.LittleEndian.AppendUint64(bz, tv.GetUint()), false
 	case Float32Type:
-		return binary.LittleEndian.AppendUint32(bz, tv.GetFloat32())
+		u32 := tv.GetFloat32()
+		if u32 == (1 << 31) {
+			u32 = 0 // normalize -0
+		}
+		_, _, _, _, isNaN = softfloat.Funpack32(u32)
+		if isNaN {
+			return bz, true
+		} else {
+			return binary.LittleEndian.AppendUint32(bz, u32), false
+		}
 	case Float64Type:
-		return binary.LittleEndian.AppendUint64(bz, tv.GetFloat64())
+		u64 := tv.GetFloat64()
+		if u64 == (1 << 63) {
+			u64 = 0 // normalize -0
+		}
+		_, _, _, _, isNaN = softfloat.Funpack64(u64)
+		if isNaN {
+			return bz, true
+		} else {
+			return binary.LittleEndian.AppendUint64(bz, u64), false
+		}
 	default:
 		panic(fmt.Sprintf(
 			"unexpected primitive value type: %s",
@@ -1443,7 +1461,7 @@ func (tv *TypedValue) GetUint64() uint64 {
 	return *(*uint64)(unsafe.Pointer(&tv.N))
 }
 
-func (tv *TypedValue) SetFloat32(n uint32) {
+func (tv *TypedValue) SetFloat32(u32 uint32) {
 	if debug {
 		if tv.T.Kind() != Float32Kind {
 			panic(fmt.Sprintf(
@@ -1451,7 +1469,7 @@ func (tv *TypedValue) SetFloat32(n uint32) {
 				tv.T.String()))
 		}
 	}
-	*(*uint32)(unsafe.Pointer(&tv.N)) = n
+	*(*uint32)(unsafe.Pointer(&tv.N)) = u32
 }
 
 func (tv *TypedValue) GetFloat32() uint32 {
@@ -1465,7 +1483,7 @@ func (tv *TypedValue) GetFloat32() uint32 {
 	return *(*uint32)(unsafe.Pointer(&tv.N))
 }
 
-func (tv *TypedValue) SetFloat64(n uint64) {
+func (tv *TypedValue) SetFloat64(u64 uint64) {
 	if debug {
 		if tv.T.Kind() != Float64Kind {
 			panic(fmt.Sprintf(
@@ -1473,7 +1491,7 @@ func (tv *TypedValue) SetFloat64(n uint64) {
 				tv.T.String()))
 		}
 	}
-	*(*uint64)(unsafe.Pointer(&tv.N)) = n
+	*(*uint64)(unsafe.Pointer(&tv.N)) = u64
 }
 
 func (tv *TypedValue) GetFloat64() uint64 {
@@ -1555,38 +1573,17 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
 	// General case.
 	bz := make([]byte, 0, 64)
 	if !omitType {
+		// TypeID is human readible and balanced, so appending ":" works.
+		// This keeps ComputeMapKey somewhat human readible esp w/
+		// colors.ColoredBytes().
 		bz = append(bz, tv.T.TypeID().Bytes()...)
 		bz = append(bz, ':') // type/value separator
 	}
 	switch bt := baseOf(tv.T).(type) {
 	case PrimitiveType:
-		const (
-			fourZeroes  = "\x00\x00\x00\x00"
-			eightZeroes = fourZeroes + fourZeroes
-		)
-		// For float types, return isNaN = true if there is a nan value,
-		// normalize to 0 if negative zero.
-		switch bt {
-		case Float32Type:
-			if tv.IsNaN() {
-				return "", true
-			}
-			if tv.GetFloat32() == (1 << 31) {
-				bz = append(bz, fourZeroes...)
-			} else {
-				bz = tv.PrimitiveBytes(bz)
-			}
-		case Float64Type:
-			if tv.IsNaN() {
-				return "", true
-			}
-			if tv.GetFloat64() == (1 << 63) {
-				bz = append(bz, eightZeroes...)
-			} else {
-				bz = tv.PrimitiveBytes(bz)
-			}
-		default:
-			bz = tv.PrimitiveBytes(bz)
+		bz, isNaN = tv.MapKeyBytes(bz)
+		if isNaN {
+			return "", true
 		}
 	case *PointerType:
 		var ptrBytes [sizeOfUintPtr]byte // zero-initialized for nil pointers
@@ -1609,6 +1606,7 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
 				if isNaN {
 					return "", true
 				}
+				bz = binary.AppendUvarint(bz, uint64(len(mk)))
 				bz = append(bz, mk...)
 				if i != al-1 {
 					bz = append(bz, ',')
@@ -1631,21 +1629,13 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
 			if isNaN {
 				return "", true
 			}
+			bz = binary.AppendUvarint(bz, uint64(len(mk)))
 			bz = append(bz, mk...)
 			if i != sl-1 {
 				bz = append(bz, ',')
 			}
 		}
 		bz = append(bz, '}')
-	case *FuncType:
-		panic("func type cannot be used as map key")
-	case *MapType:
-		panic("map type cannot be used as map key")
-	case *InterfaceType:
-		panic("should not happen")
-	case *PackageType:
-		pv := tv.V.(*PackageValue)
-		bz = append(bz, []byte(strconv.Quote(pv.PkgPath))...)
 	case *ChanType:
 		panic("not yet implemented")
 	default:
```

File: gnovm/pkg/gnolang/values.go [hunk 1]
```diff
@@ -1585,6 +1598,10 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
 			} else {
 				bz = tv.PrimitiveBytes(bz)
 			}
+		case StringType:
+			sv := tv.GetString()
+			bz = binary.AppendUvarint(bz, uint64(len(sv))<<2|maskStringLength)
+			bz = append(bz, sv...)
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go]: kinda works but brittle... if PrimitiveBytes were to support varlength types in the future besides strings it would become a problem two ways: case is missing, and can't add another case anyways.

also redundant when the length prefix isn't necessary.

File: gnovm/pkg/gnolang/values.go [hunk 2]
```diff
@@ -1600,7 +1617,7 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
 	case *ArrayType:
 		av := tv.V.(*ArrayValue)
 		al := av.GetLength()
-		bz = append(bz, '[')
+		bz = binary.AppendUvarint(bz, uint64(al)<<2|maskArrayLength)
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go]: sorta works but brittle because if omitTypes=false for an interface array everything that is varlength must be uvarint prefixed, which probably is the case but not with future types.

also the [,,,] helps with debugging w/ coloredBytes whereas this is really hard to parse even with ColoredBytes.

File: gnovm/pkg/gnolang/values.go [hunk 3]
```diff
@@ -1610,20 +1627,16 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
...
 			bz = append(bz, av.Data...)
 		}
-		bz = append(bz, ']')
 	case *SliceType:
 		panic("slice type cannot be used as map key")
 	case *StructType:
 		sv := tv.V.(*StructValue)
 		sl := len(sv.Fields)
-		bz = append(bz, '{')
+		bz = binary.AppendUvarint(bz, uint64(sl)<<2|maskStructLength)
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go]: ditto. the [,,,] and {,,,} distinction really does help with debugging.

as with array, my suggested diff in the PR comments is less brittle. it's a bit less efficient but seems like it's worth it esp for debugging primitive bytes.

File: gnovm/pkg/gnolang/values.go [hunk 4]
```diff
@@ -1543,20 +1542,34 @@ func (tv *TypedValue) AssertNonNegative(msg string) {
...
+
 	if tv.T == nil {
 		if debug {
 			if omitType {
 				panic("should not happen")
 			}
 		}
-		return nilStr, false
+		// considered as "zero type id"
+		return "\x00", false
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go]: "nil" helps with debugging better. it helps to see "[nil,nil,nil,nil]" etc.
I don't think the extra bytes are much slower since it uses a fast algo unlike sha hashing.

File: gnovm/pkg/gnolang/values.go [hunk 5]
```diff
@@ -1543,20 +1542,34 @@ func (tv *TypedValue) AssertNonNegative(msg string) {
...
+	)
+
 	// General case.
 	bz := make([]byte, 0, 64)
 	if !omitType {
-		bz = append(bz, tv.T.TypeID().Bytes()...)
-		bz = append(bz, ':') // type/value separator
+		typeid := tv.T.TypeID()
+		bz = binary.AppendUvarint(bz, uint64(len(typeid))<<2|maskTypeID)
+		bz = append(bz, typeid...)
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go]: in my diff pasted in the PR comments I preserve the ":" because the typeid is human read/parseable. 
so it helps with debugging and it's also more efficient as there is no varint prefix needed.

File: gnovm/pkg/gnolang/values.go (hunk 3 above)
Comment (jaekwon) [reply gnovm/pkg/gnolang/values.go]: But in my diff there is no varint prefix for types, so for interface fields it's just as efficient overall.

File: gnovm/pkg/gnolang/values.go (hunk 2 above)
Comment (thehowl) [reply gnovm/pkg/gnolang/values.go]: I fear what may be the future types you intend to add ;P

File: gnovm/pkg/gnolang/values.go [hunk 6]
```diff
@@ -1555,38 +1560,17 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
 	// General case.
 	bz := make([]byte, 0, 64)
 	if !omitType {
+		// TypeID is human readible and balanced, so appending ":" works.
```
Comment (davd-gzl) [inline gnovm/pkg/gnolang/values.go]:
```suggestion
		// TypeID is human readable and balanced, so appending ":" works.
```

File: gnovm/pkg/gnolang/values.go [hunk 7]
```diff
@@ -1555,38 +1560,17 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (key MapKey, isN
...
+		// This keeps ComputeMapKey somewhat human readible esp w/
```
Comment (davd-gzl) [inline gnovm/pkg/gnolang/values.go]:
```suggestion
		// This keeps ComputeMapKey somewhat human readable esp w/
```

File: gnovm/pkg/gnolang/values_test.go [hunk 8]
```diff
@@ -76,3 +79,69 @@ func TestGetLengthPanic(t *testing.T) {
...
+		{
+			`[2]string{"hi,\x07wor", "ld"}`,
+			"[2]string:[\x07hi,\x07wor,\x02ld]",
+			false,
+		},
+		{
+			`[2]string{"hi", "wor,\x02ld"}`,
+			"[2]string:[\x02hi,\x07wor,\x02ld]",
+			false,
+		},
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values_test.go:146]:
```suggestion
		},
		{
			`struct{a string; b string}{"x", "y,z"}`,
			"struct{main.a string;main.b string}:{\x01x,\x03y,z}",
			false,
		},
		{
			`struct{a string; b string}{"x,y", "z"}`,
			"struct{main.a string;main.b string}:{\x03x,y,\x01z}",
			false,
		},
```

File: gnovm/pkg/gnolang/values.go [hunk 9]
```diff
@@ -1100,35 +1086,54 @@ func (tv TypedValue) unrefCopy(alloc *Allocator, store Store) (cp TypedValue) {
...
+		u32 := tv.GetFloat32()
+		if u32 == (1 << 31) {
+			u32 = 0 // normalize -0
+		}
+		_, _, _, _, isNaN = softfloat.Funpack32(u32)
+		if isNaN {
+			return bz, true
+		} else {
+			return binary.LittleEndian.AppendUint32(bz, u32), false
+		}
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go:1122]:
```suggestion
		u32 := tv.GetFloat32()
		if u32 == 0 || u32 == (1 << 31) {
			// if -0.0, normalize to 0.0.
			return binary.LittleEndian.AppendUint32(bz, 0), false
		}
		if _, _, _, _, isNaN = softfloat.Funpack32(u32); isNaN {
		        return bz, true
		}
	        return binary.LittleEndian.AppendUint32(bz, u32), false
```

File: gnovm/pkg/gnolang/values.go [hunk 10]
```diff
@@ -1100,35 +1086,54 @@ func (tv TypedValue) unrefCopy(alloc *Allocator, store Store) (cp TypedValue) {
...
+		u64 := tv.GetFloat64()
+		if u64 == (1 << 63) {
+			u64 = 0 // normalize -0
+		}
+		_, _, _, _, isNaN = softfloat.Funpack64(u64)
+		if isNaN {
+			return bz, true
+		} else {
+			return binary.LittleEndian.AppendUint64(bz, u64), false
+		}
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go:1131]:
```suggestion
		u64 := tv.GetFloat64()
		if u64 == 0 || u64 == (1 << 63) {
		        // if -0.0, normalize to 0.0.
		        return binary.LittleEndian.AppendUint64(bz, 0), false
		}
		if _, _, _, _, isNaN = softfloat.Funpack64(u64); isNaN {
			return bz, true
		}
		return binary.LittleEndian.AppendUint64(bz, u64), false
```

File: gnovm/pkg/gnolang/values_test.go [hunk 11]
```diff
@@ -76,3 +79,79 @@ func TestGetLengthPanic(t *testing.T) {
...
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values_test.go:146]:
```suggestion
		},
		{
			// With Elem type.
			`[2]interface{}{"hi,wor", int64(1)}`,
			"[2]interface{}:[\rstring:hi,wor,\x0eint64:\x01\x00\x00\x00\x00\x00\x00\x00]",
			false,
		},
		{
			// With Elem type.
			`struct{a interface{}; b interface{}}{"hi,wor", int64(1)}`,
			"struct{main.a interface{};main.b interface{}}:{\rstring:hi,wor,\x0eint64:\x01\x00\x00\x00\x00\x00\x00\x00}",
			false,
		},
```

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/values_test.go:146]: with type.
