### PR TITLE
fix(gnovm): runtime panic when using nil as key

### LINKED ISSUE #4500: gnovm: Runtime Panic When Using `nil` as Key in `map[*int]int`
**Issue Description:**

When executing the code snippet below, a runtime panic occurs in the Gno VM:

```golang
package main

import "strconv"

type stringMap map[*int]int

var (
    a        int = 1
    accounts     = stringMap{}
    ptr          = &a
)

func Register() {
    accounts[ptr] = 1
    accounts[nil] = 1
}

func main() {
    Register()
}
```

**Expected Behavior:**

The code is expected to execute without errors, initializing `accounts` with values mapped to `ptr` and `nil`.

**Actual Behavior:**

The program crashes with the following stack trace:

```
stacktrace:
        Register<VPBlock(3,4)>()
            main/map36.gno:15
        main<VPBlock(1,5)>()
            main/map36.gno:19
        
        stack:
        goroutine 19 [running]:
        runtime/debug.Stack()
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/debug/stack.go:26 +0x64
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).runTest.func1()
                /Users/ghost/Documents/projects/gno/gnovm/pkg/test/filetest.go:264 +0xb8
        panic({0x104c4d740?, 0x14003277890?})
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/panic.go:792 +0x124
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run.func1()
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:1245 +0x174
        panic({0x104c4d740?, 0x14003277890?})
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/panic.go:792 +0x124
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*TypedValue).ComputeMapKey(0x14000424078, {0x104d424b0, 0x14000398000}, 0xec?)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/values.go:1542 +0x868
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*MapValue).GetPointerForKey(0x14002433220, 0x0, {0x104d424b0, 0x14000398000}, 0x14000424078)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/values.go:726 +0x44
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*TypedValue).GetPointerAtIndex(0x14000424050, 0x104d35358?, {0x104d424b0, 0x14000398000}, 0x14000424078)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/values.go:1943 +0x25c
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).PopAsPointer2(0x140003582c8, {0x104d3b9f0?, 0x140030a6930?})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:2272 +0x1fc
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).PopAsPointer(0x140003582c8, {0x104d3b9f0, 0x140030a6930})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:2217 +0x2c
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).doOpAssign(0x140003582c8)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/op_assign.go:30 +0x1bc
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run(0x140003582c8, {0x10495b4cc?, 0x14001150200?})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:1504 +0x994
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunStatement(0x140003582c8, {0x10495b4cc, 0x8}, {0x104d3bf00, 0x14003269c70})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:909 +0x314
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).runFunc(0x140003582c8, {0x10495b4cc, 0x8}, {0x104957604, 0x4}, 0xd0?)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:753 +0x3ac
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunMain(...)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/machine.go:757
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).runTest(0x140000c8540, 0x140003582c8, {0x104957604, 0x4}, {0x14000342810?, 0x104d2abe0?}, {0x14000352600, 0xf8, 0x14000398000?}, {0x0, ...})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/test/filetest.go:311 +0x950
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).runFiletest(0x140000c8540, {0x14000342810, 0x9}, {0x14000352600, 0xf8, 0x200})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/test/filetest.go:68 +0x5e8
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).RunFiletest(0x140000d43c0?, {0x14000342810?, 0x0?}, {0x14000352600?, 0x1050ed7f0?, 0x104d84c3c?})
                /Users/ghost/Documents/projects/gno/gnovm/pkg/test/filetest.go:30 +0x7c
        github.com/gnolang/gno/gnovm/pkg/gnolang_test.TestFiles.func2.4(0x14000102e00)
                /Users/ghost/Documents/projects/gno/gnovm/pkg/gnolang/files_test.go:106 +0xb8
        testing.tRunner(0x14000102e00, 0x140003548c0)
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/testing/testing.go:1792 +0xe4
        created by testing.(*T).Run in goroutine 5
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/testing/testing.go:1851 +0x374
```

### LINKED ISSUE #4507: gnovm: Runtime Panic When Using struct with nil ptr field value as Key in map[struct]int
### Description

panic:

```go
type PrivateData struct {
	Name  string
	Value int
	Tree  *avl.Tree
}

func SaveMapWithPrivateKeyToPublicRealm(cur realm) {
	m := make(map[PrivateData]string)
	key := PrivateData{Name: "key", Value: 100}
	m[key] = "test"
}
```

fill the ptr with avl.NewTree() would making it works
removing the field Tree would make it works too

think it's related to: https://github.com/gnolang/gno/issues/4500
maybe this issue too: https://github.com/gnolang/gno/issues/4280

### PR DESCRIPTION
**Pull request by omarsy**
Fixes #4500, fixes #4507

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
 🟢 Pending initial approval by a review team member, or review from tech-staff


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: omarsy/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

<details><summary>Pending initial approval by a review team member, or review from tech-staff</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 Not (🔴 Pull request author is a member of the team: tech-staff)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 If
    ├── 🟢 Condition
    │   └── 🟢 Or
    │       ├── 🟢 At least 1 user(s) of the organization reviewed the pull request (with state "APPROVED")
    │       ├── 🟢 At least 1 user(s) of the team tech-staff reviewed pull request
    │       └── 🔴 This pull request is a draft
    └── 🟢 Then
        └── 🟢 And
            ├── 🟢 Not (🔴 This label is applied to pull request: review/triage-pending)
            └── 🟢 At least 1 user(s) of the team tech-staff reviewed pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

**Comment by mvallenet** [comment]
this snippet crash too:

```go
type PrivateData struct {
	Name  string
	Value int
	Ptr   *int
}

func SaveMapWithPrivateKeyToPublicRealm(cur realm) {
	m := make(map[PrivateData]string)
	key := PrivateData{Name: "key", Value: 100}
	m[key] = "public value"
}
```

could be nice to add a test about this to see if your fix works for this too

**Comment by omarsy** [comment]
> this snippet crash too:
> 
> ```go
> type PrivateData struct {
> 	Name  string
> 	Value int
> 	Ptr   *int
> }
> 
> func SaveMapWithPrivateKeyToPublicRealm(cur realm) {
> 	m := make(map[PrivateData]string)
> 	key := PrivateData{Name: "key", Value: 100}
> 	m[key] = "public value"
> }
> ```
> 
> could be nice to add a test about this to see if your fix works for this too

I don't think this is related to my issue. It's more related to this issue: https://github.com/gnolang/gno/issues/4280. Or maybe it is already fixed by this https://github.com/gnolang/gno/pull/4385

**Comment by mvallenet** [comment]
> > this snippet crash too:
> > ```go
> > type PrivateData struct {
> > 	Name  string
> > 	Value int
> > 	Ptr   *int
> > }
> > 
> > func SaveMapWithPrivateKeyToPublicRealm(cur realm) {
> > 	m := make(map[PrivateData]string)
> > 	key := PrivateData{Name: "key", Value: 100}
> > 	m[key] = "public value"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > could be nice to add a test about this to see if your fix works for this too
> 
> I don't think this is related to my issue. It's more related to this issue: #4280. Or maybe it is already fixed by this #4385

idk because if i remove the ptr field it works & i will try to fil the ptr see if it fix the bug & i will open issue then so i can have more insights

**Comment by jefft0** [comment]
Hi @omarsy . Can you merge master to see if it fixes the failed CI check for lint?

**Comment by jefft0** [comment]
The Go Test check fails with "fatal error: concurrent map writes". That's a weird error. Do you think it's related to your PR? (If not, then we need to get someone to look at it.)

**Comment by omarsy** [comment]
> The Go Test check fails with "fatal error: concurrent map writes". That's a weird error. Do you think it's related to your PR? (If not, then we need to get someone to look at it.)

It seems it is not related my issue.  it seems it  is a concurrency issue

File: gnovm/pkg/gnolang/values.go [hunk 1]
```diff
@@ -1546,6 +1546,11 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
 		bz = append(bz, pbz...)
 	case *PointerType:
 		fillValueTV(store, tv)
+		// nil pointer.
+		if tv.V == nil {
+			bz = append(bz, nilStr...)
```
Comment (thehowl) [inline gnovm/pkg/gnolang/values.go]: Let's use `nilStr` when we have interfaces.

For this case, I'd say the most correct is actually:

```
var x [sizeOfUintPtr]byte
bz = append(bz, x[:]...)
```

So that it's all 0 bytes, as nil pointers are.

**Review by thehowl — COMMENTED** [review]
Could we not include #4507 as another regression test? (and issue that is fixed?)

File: gnovm/pkg/gnolang/values.go (hunk 1 above)
Comment (omarsy) [reply gnovm/pkg/gnolang/values.go]: right done here https://github.com/gnolang/gno/pull/4505/commits/dbee3b3cdb787451ba89bdafbb8926f1e57d6021

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/values.go]: also here?

```diff
--- a/gnovm/pkg/gnolang/values.go
+++ b/gnovm/pkg/gnolang/values.go
@@ -1532,6 +1532,7 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
                                panic("should not happen")
                        }
                }
+               // Also here to be consistent?
                return MapKey(nilStr)
        }
```

Comment (thehowl) [reply gnovm/pkg/gnolang/values.go]: @ltzmaxwell That's the case of the nil interface, I think it makes sense there
