### PR TITLE
fix: hardcode max vm cycles in keeper

### LINKED ISSUE #1805: Infinite loops unhandled
Props to @leohhhn for identifying this.

When the gno vm encounters an infinite loop, it is never able to finish execution.  It should probably stop after a certain number of CPU cycles.

Here is an example using recursion:
```go
package main

func main() {
    println(recurse())
}

func recurse() int {
    return recurse()
}

```

And an example using a for loop:
```go
package main

func main() {
    var n int
    for {
        n++
    }
    println(n)
}
```

Both of these will cause the vm to hang.

### PR DESCRIPTION
**Pull request by deelawn**
This hardcodes the maximum VM cycles in the keeper to ten million, the same that is currently being used from genesis. It doesn't seem like there is a reason why we should want people to be able to adjust this.
<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

File: gnovm/pkg/gnolang/machine.go [hunk 1]
```diff
@@ -75,6 +75,7 @@ type MachineOptions struct {
 	Alloc         *Allocator // or see MaxAllocBytes.
 	MaxAllocBytes int64      // or 0 for no limit.
 	MaxCycles     int64      // or 0 for no limit.
+	IsTest        bool
```
Comment (thehowl) [inline gnovm/pkg/gnolang/machine.go:78]: wdyt if instead of adding `IsTest`, we made `MaxAllocBytes` and `MaxCycles` have default values if `== 0`, and be unlimited if `< 0`?

File: gnovm/pkg/gnolang/machine.go [hunk 2]
```diff
@@ -99,6 +100,10 @@ func NewMachineWithOptions(opts MachineOptions) *Machine {
 	checkTypes := opts.CheckTypes
 	readOnly := opts.ReadOnly
 	maxCycles := opts.MaxCycles
+	if !opts.IsTest && maxCycles == 0 {
+		// Never allow an infinite number of cycles.
+		maxCycles = 10_000_000
```
Comment (thehowl) [inline gnovm/pkg/gnolang/machine.go:105]: can we centralize this in a constant like DefaultMaxCycles?

**Review by thehowl — COMMENTED** [review]
I'm not entirely sure about these changes.

If you execute these on Gno.land, these will fail, I'm pretty sure, as you'd get "cpu cycle overrun" already. So these fail in `gno run` and `gno test`, which from this PR would be excluded with the new limit.

The way I see it, we should have a limit on the amount of frames that can be created (ie. a stack overflow error), which is for both local testing and the blockchain context, but nothing more than the existing CPU overrun checks for infinte for loops. wdyt?

**Comment by thehowl** [comment]
<details><summary>Initial comment</summary>
<p>

From the review meeting:

- Let's make sure that `gno run` and `gno test` are not limited in VM cycles execution
- And have a default value for max VM cycles


</p>
</details> 

TBD w/ @deelawn @piux2

**Review by petar-dambovaliev — CHANGES_REQUESTED** [review]
In my opinion, the bottom of infinite recursion/loop should be when there is no more gas.

**Comment by piux2** [comment]
also we need to remove the code that configs VM parameters from command flag.

**Comment by deelawn** [comment]
> In my opinion, the bottom of infinite recursion/loop should be when there is no more gas. That means that the check needs to be added in the VM.

This will be the fallback value if, for some reason, something prevents the machine from halting execution when the gas runs out.

**Review by petar-dambovaliev — APPROVED** [review]

**Comment by moul** [comment]
Hey, 

I support this change. But in the long time, I believe we should make it configurable by the blockchain instead of hardcoding it. See #1856.

Also, linked with #828.

**Comment by zivkovicmilos** [comment]
> Hey,
> 
> I support this change. But in the long time, I believe we should make it configurable by the blockchain instead of hardcoding it. See #1856.
> 
> Also, linked with #828.

💯 % agreed. I'll see to tackle this soon

**Review by piux2 — COMMENTED** [review]
LGTM
