### PR TITLE
fix: (gnovm) star expr assign for #1919

### LINKED ISSUE #1326: unexpected unreal object when assigning a local variable to a global variable (pointer)
https://gist.github.com/thehowl/e36b0f0d652a2a348a2fcd331a310417

(added as a txtar test `gnoland/cmd/gnoland/testdata`)

Changing `*el = n` to `el = &n` fixed the issue. Found while trying to reproduce #1167

### PR DESCRIPTION
**Pull request by jaekwon**
This is a complete solution, alternative to #1919, and (I think) closes #1326.
It creates a new container for "baseless" (floating) values constructed via `new(xxx)` or `&struct{}`, which currently do not have a base containing object for that value, and are currently represented as PointerValues with .Base set to nil.

The containing object is like a Block but minimal -- it only contains one Value, and has no Source or Parent. The modifications to realm.go allow for proper ref-counting so that even when there are multiple references to the baseless value, and even when the value is primitive, gc and ref-counting works (since the containing HeapItemValue is ref-counted). PointerValue.Base should now never be nil.

See also https://github.com/gnolang/gno/pull/1919#issuecomment-2144059991 for why the previous solution doesn't work. 

A better optimization than the one mentioned in the comment above, is to always store the HeapItemValue along with the Value, since the Value's refcount should always be 1. This is left for the future, after first checking that this invariant is true.

### CODE REVIEW

File: gnovm/pkg/gnolang/ownership.go [hunk 1]
```diff
@@ -359,6 +362,9 @@ func (tv *TypedValue) GetFirstObject(store Store) Object {
 		oo := store.GetObject(cv.ObjectID)
 		tv.V = oo
 		return oo
+	case *HeapItemValue:
+		// should only appear in PointerValue.Base
+		panic("should not happen")
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/ownership.go:361]: HeapItemValue never appears otherwise, except as Base to PointerValue. 
This defensive check should help in the future.

File: gnovm/pkg/gnolang/realm.go [hunk 2]
```diff
@@ -1054,7 +1053,7 @@ func copyTypeWithRefs(typ Type) Type {
 // persistence bytes serialization.
 // Also checks for integrity of immediate children -- they must already be
 // persistent (real), and not dirty, or else this function panics.
-func copyValueWithRefs(parent Object, val Value) Value {
+func copyValueWithRefs(val Value) Value {
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/realm.go:1056]: parent was not used at all.

File: gnovm/pkg/gnolang/realm.go [hunk 3]
```diff
@@ -1067,33 +1066,25 @@ func copyValueWithRefs(parent Object, val Value) Value {
...
+			*/
+			Base:  toRefValue(cv.Base),
+			Index: cv.Index,
 		}
 	case *ArrayValue:
 		if cv.Data == nil {
 			list := make([]TypedValue, len(cv.List))
 			for i, etv := range cv.List {
-				list[i] = refOrCopyValue(cv, etv)
+				list[i] = refOrCopyValue(etv)
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/realm.go:1087]: likewise cv was not used at all.

File: gnovm/pkg/gnolang/uverse.go [hunk 4]
```diff
@@ -894,16 +894,18 @@ func UverseNode() *PackageNode {
...
 				}),
 				V: PointerValue{
-					TV: &TypedValue{
-						T: tt,
-						V: vv,
-					},
-					Base: nil,
+					TV:    &hi.Value,
+					Base:  hi,
+					Index: 0,
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/uverse.go:908]: Notice that TV must be set manually to &HIV.Value.

File: gnovm/tests/files/zrealm3.gno [hunk 5]
```diff
@@ -57,18 +57,37 @@ func main() {
...
+//     "Value": {
+//         "T": {
+//             "@type": "/gno.RefType",
+//             "ID": "gno.land/r/test.Node"
+//         },
+//         "V": {
+//             "@type": "/gno.RefValue",
+//             "Hash": "567a18d9c7594ece7956ce54384b0858888bb834",
+//             "ObjectID": "a8ada09dee16d791fd406d629fe29bb0ed084a30:7"
+//         }
```
Comment (jaekwon) [inline gnovm/tests/files/zrealm3.gno:82]: You can tell it's a HeapItemValue because it has one field, "Value".
(we could update the tests to show the type in the future for clarity,
like `c[a8ada09dee16d791fd406d629fe29bb0ed084a30:6]=*HeapItemValue{`

Comment (jaekwon) [reply gnovm/tests/files/zrealm3.gno:82]: While this could be eliminated with some intelligence prior to persistence,
to unwrap the HeapItemValue in case where the HeapItemValue only has refcount of 1,
1. The HeapItemValue is necessary when the .Value is a primitive non-object anyways, and
2. This would mean PointerValue.Base is nil, and we'd need additional logic to re-wrap when necessary.
3. And with the above point, it's not clear the result would be any faster.
But this is something we could explore after launch.

File: gnovm/pkg/gnolang/realm.go [hunk 6]
```diff
@@ -822,11 +816,10 @@ func getChildObjects(val Value, more []Value) []Value {
 	case DataByteValue:
 		panic("cannot get children from data byte objects")
 	case PointerValue:
-		if cv.Base != nil {
-			more = getSelfOrChildObjects(cv.Base, more)
-		} else {
-			more = getSelfOrChildObjects(cv.TV.V, more)
+		if cv.Base == nil {
+			panic("should not happen")
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/realm.go:820]: With this PR, PointerValue.Base should never be nil during finalization.

**Comment by grepsuzette** [comment]
This seems a great solution, avoiding nil `Base` and minimal code.

File: gnovm/pkg/gnolang/realm.go (hunk 6 above)
Comment (deelawn) [inline gnovm/pkg/gnolang/realm.go:820]:
```suggestion
			panic("pointer base should not be nil")
```

File: gnovm/pkg/gnolang/ownership.go [hunk 7]
```diff
@@ -359,6 +356,9 @@ func (tv *TypedValue) GetFirstObject(store Store) Object {
...
```
Comment (deelawn) [inline gnovm/pkg/gnolang/ownership.go:361]:
```suggestion
		panic("heap item value should only appear as a pointer's base")
```

File: gnovm/pkg/gnolang/realm.go [hunk 8]
```diff
@@ -1205,6 +1196,24 @@ func copyValueWithRefs(parent Object, val Value) Value {
...
+		//
+		//  1.  The HeapItemValue is necessary when the .Value is a
+		//    primitive non-object anyways, and
+		//  2. This would mean PointerValue.Base is nil, and we'd need
+		//    additional logic to re-wrap when necessary, and
+		//  3. And with the above point, it's not clear the result
+		//    would be any faster.  But this is something we could
+		//    explore after launch.
+		hiv := &HeapItemValue{
+			ObjectInfo: cv.ObjectInfo.Copy(),
```
Comment (deelawn) [inline gnovm/pkg/gnolang/realm.go:1213]: This is more of a general question -- why must the object info be copied in this function?

File: gnovm/pkg/gnolang/uverse.go (hunk 4 above)
Comment (deelawn) [inline gnovm/pkg/gnolang/uverse.go:908]:
```suggestion
```

File: gnovm/pkg/gnolang/machine.go [hunk 9]
```diff
@@ -1934,9 +1934,11 @@ func (m *Machine) PopAsPointer(lx Expr) PointerValue {
 		return ptr
 	case *CompositeLitExpr: // for *RefExpr
 		tv := *m.PopValue()
+		hv := m.Alloc.NewHeapItem(tv)
 		return PointerValue{
-			TV:   &tv, // heap alloc
-			Base: nil,
+			TV:    &hv.Value,
+			Base:  hv,
+			Index: 0,
```
Comment (deelawn) [inline gnovm/pkg/gnolang/machine.go:1941]:
```suggestion
```

**Review by deelawn — APPROVED** [review]

File: gnovm/pkg/gnolang/realm.go (hunk 6 above)
Comment (grepsuzette) [reply gnovm/pkg/gnolang/realm.go:821]: Since the call stack is shown during a panic, I'd argue `panic("should not happen")` is better:

 - Clearly conveys the unexpected nature of the situation. It indicates that the program has encountered a state that was not anticipated during development.
- Can serve as a strong signal to developers that there may be a serious issue in the code that needs to be addressed.
- Also, more readable (you read it instantly as opposed to reading the whole message)

File: gnovm/pkg/gnolang/realm.go (hunk 8 above)
Comment (petar-dambovaliev) [reply gnovm/pkg/gnolang/realm.go:1214]: I think, just because we copy the object info everywhere else in this function.

**Review by petar-dambovaliev — APPROVED** [review]
lgtm

File: gnovm/pkg/gnolang/realm.go (hunk 6 above)
Comment (thehowl) [reply gnovm/pkg/gnolang/realm.go:821]: We obviously have a screwed up situation here, because panics are explicitly meant for extraordinary situations rather than mundane error handling, but it is clearly not the case in Gno's codebase. This issue has already been discussed in issues, and unfortunately it's not going to change. I am of the strong opinion, though, that we should NOT use "should not happen" even in these situations; for the simple reason that most error situations WILL happen with incorrect usage; and with a tool such as a parser/VM, incorrect usage is to be expected.

I'm OK with making error messages like "should not happen: <error messages>". But we need to have error messages that explain to the user what's going on without digging deep in the codebase.

Comment (thehowl) [reply gnovm/pkg/gnolang/realm.go:821]: In any case; I'm going to open a PR so we can have this in our contributing guidelines, so we can also have a discussion to set out clear rules

Comment (jaekwon) [reply gnovm/pkg/gnolang/realm.go:821]: > We obviously have a screwed up situation here, because panics are explicitly meant for extraordinary situations rather than mundane error handling, but it is clearly not the case in Gno's codebase. This issue has already been discussed in issues, and unfortunately it's not going to change.

Not really. Extraordinary is not the right definition. It's clearly also used for user errors, for example all across the standard libraries. Generally, panics are used when there is no way to handle the error, and the convenience of unrolling the stack is desired. Like user errors.

## Benefits of panic'ing

1. Security - I'm going to quote Cheney here: `I consider the argument that "Developers forget to check error codes" is cancelled out by the counter argument "Developers forget to handle exceptions". Either may be true, depending on the language you are basing your argument on, but neither commands a winning position.` In our application, there is a winning position. **forget to check values:** If we returned an error instead of panicking for storage or memory allocation issues, or even worse, general VM operation exceptions, developers including myself will absolutely forget to handle some exceptions correctly, and they will lead to bugs in the blockchain, and probably an exploit. **forget to handle exceptions:** on the other hand, this doesn't apply because we already handle it at the transaction level, and beyond that there is nothing else to do. The security benefit of our panic usage is massive and real. 
2. Convenience - It definitely reduces the amount of code we have to write, because we can panic.
3. Legibility - the code is actually easier to understand this way, leading to benefits for security as well. 

## Why our use-case is different;

1. It's a VM - a lot of panics are due to invalid use (invalid gno code). these are user errors, and user errors generally cannot be handled. 
2. Determinism - handling a storage error and trying to handle a storage error would result in nondeterminism, there really is nothing to be done here. Not true with most software. Also, blockchain nodes are supposed to have sufficient storage.
3. Transactional - we have clear transaction boundaries at the blockchain level, and we need to roll *everything* back upon a transaction failure (except the antehandler fee/sequence stuff). Usage of recover() is *necessary* here for the security of the project (esp since bugs happen) anyways, so if we're not doing complex logic flow based on the panic value, which we don't, that's less reasons to avoid using panics. 
4. Legibility - The Gno VM is intended to serve as functional production software, but also a spec that is easy to understand. This isn't true for most software.

--------------

This conversation would be more constructive if we discussed the actual problem resulting from panic usage. What is the specific problem from our usage of panics, generally speaking, besides "we're not supposed to"? 

Example;

**Problem 1: internal exception management hell**: The main reason why panics are frowned upon is because of the blowup of exception management as seen in Java. We don't have this issue with panic management, because there's nothing more to do when encountering preprocessor panics (gno programmer error), memory allocation limits (roll back tx), or storage issues (which *are* exceptional on our use-case, and cannot be handled because we need replicated determinism, roll back tx).

**Problem 2: exception management hell for library users**: For users of the GnoVM, we can recover, and rather than panic as we already do, we can return an error. Say, from Machine.Run, so that users of our VM don't have to catch panics, but can handle an error instead. But we should continue to panic within the VM code for storage or memory issues, because there is no way to recover from these situations within the VM.

> The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values. - https://go.dev/blog/defer-panic-and-recover

--------------

Note on convenience: 

Question: why panic at all then, when errors could be trickled up to the main function or top of goroutine and program aborted there? The answer is convenience. For us, we take advantage of this convenience because we do in fact want to abort the whole transaction, and there is no custom error handling to be done.

Example of convenience in action: 
JSON/encode uses internal panics to unroll the stack.
https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/encoding/json/encode.go

Comment (jaekwon) [reply gnovm/pkg/gnolang/realm.go:821]: "should not happen" is mostly a convenience for when the panic cause is clear by inspecting the code;
But I agree, when the panic is expected to happen frequently due to user error, or when the user would benefit from the error message, we can modify the message to be more informative.

File: gnovm/pkg/gnolang/machine.go (hunk 9 above)
Comment (jaekwon) [reply gnovm/pkg/gnolang/machine.go:1963]: I think 0 is nice... HIV are expected to have value 0, we could maybe extend it to allow a limited number in the future, say for grouping 1-refcount objects together with their parent.

File: gnovm/pkg/gnolang/realm.go (hunk 8 above)
Comment (jaekwon) [reply gnovm/pkg/gnolang/realm.go:1214]: It is used by reference *ObjectInfo, so if we don't copy it, the HeapItemValue would end up having the containing value's object ID, instead of there being two distinct ones, and the system would crash after it tramples the value with a heapitemvalue containing... itself.

File: gnovm/pkg/gnolang/machine.go (hunk 9 above)
Comment (deelawn) [reply gnovm/pkg/gnolang/machine.go:1963]: I only suggested removing it because the default value for this type is 0, so no need to set it unless it is being set to a non-default value.

File: gnovm/pkg/gnolang/values.go [hunk 10]
```diff
@@ -171,6 +173,9 @@ func (dbv DataByteValue) SetByte(b byte) {
 // or binary operations. When a pointer is to be
 // allocated, *Allocator.AllocatePointer() is called separately,
 // as in OpRef.
+//
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go:176]: the comments above should be updated as well.

File: gnovm/pkg/gnolang/values.go [hunk 11]
```diff
@@ -171,6 +173,9 @@ func (dbv DataByteValue) SetByte(b byte) {
...
+// Since PointerValue is used internally for assignment etc,
+// it MUST stay minimal for computational efficiency.
 type PointerValue struct {
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go:179]: the original comment on this should be updated as well.
''...A pointer constructed via a &x{} composite lit expression or constructed via new() or make() are independent objects, and have nil Base...."
