### PR TITLE
fix: achieve type assertion parity with go

### LINKED ISSUE #1650: type assertion on recovered `nil`s panics
```go
package main

type ex int

func (ex) Error() string { return "" }

func main() {
	defer func() {
		e := recover()
		if _, ok := e.(ex); ok {
			println("wat")
		} else {
			println("ok")
		}
	}()
}
```

<details><summary>Output and stacktrace</summary>
<p>

```
panic running expression main(): runtime error: invalid memory address or nil pointer dereference
Machine:
    CheckTypes: false
	Op: [OpHalt OpReturnFromBlock OpReturnCallDefers OpBody OpPopBlock OpIfCond OpEval OpDefine]
	Values: (len: 3)
          #2 (typeval{main.ex (0xc000119440)} type{})
          #1 (undefined)
          #0 (main func()())
	Exprs:
          #0 ok<VPBlock(1,0)>
	Stmts:
          #1 _<VPBlock(0,0)>, ok<VPBlock(1,0)> := e<VPBlock(2,0)>.(ex<VPBlock(5,0)>)
          #0 bodyStmt[0/0/2]=(end)
	Blocks:
          @(1) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e960,Source:if _<VPBlock(0,0)>, ok<VPBlock(1...,Parent:0xc00035e5a0)
            ok: (undefined)
 (s vals) @(1) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000266d20,Source:if _<VPBlock(0,0)>, ok<VPBlock(1...,Parent:0xc000344020)
            ok: (false bool)
 (s typs) @(1) [bool]
          @(2) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e5a0,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc00035e3c0)
            e: (undefined)
 (s vals) @(2) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000344020,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc000335420)
            e: (undefined)
 (s typs) @(2) [interface{}]
          @(3) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e3c0,Source:func main() { defer func func(){...,Parent:0xc00035e000)
 (s vals) @(3) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000335420,Source:func main() { defer func func(){...,Parent:0xc0002cf820)
 (s typs) @(3) []
          @(4) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e000,Source:file{ package main; type ex (con...,Parent:0xc0002ca5a0)
 (s vals) @(4) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc0002cf820,Source:file{ package main; type ex (con...,Parent:0xc0002cfb20)
 (s typs) @(4) []
          @(5) main
	Blocks (other):
          #2 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e5a0,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc00035e3c0)
            e: (undefined)
 (static) #2 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000344020,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc000335420)
            e: (undefined)
          #1 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e3c0,Source:func main() { defer func func(){...,Parent:0xc00035e000)
 (static) #1 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000335420,Source:func main() { defer func func(){...,Parent:0xc0002cf820)
	Frames:
          #0 [FRAME FUNC:main RECV:(undefined) (0 args) 1/0/0/0/1 LASTPKG:main LASTRLM:Realm(nil)]
	Realm:
	  
	Exceptions:
	  []
	  
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa1ac29]

goroutine 1 [running]:
main.runExpr.func1()
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:159 +0x125
panic({0xbcb520?, 0x135cc90?})
	/usr/lib/go/src/runtime/panic.go:914 +0x21f
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).doOpTypeAssert2(0xc000166fc0)
	/home/howl/oc/gno/gnovm/pkg/gnolang/op_expressions.go:318 +0x5a9
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run(0xc000166fc0)
	/home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:1265 +0xd8e
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Eval(0xc000166fc0, {0xe7fb18, 0xc000119860})
	/home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:701 +0x579
main.runExpr(0xc000166fc0, {0xc9823d?, 0x1?})
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:166 +0x8d
main.execRun(0xc000291770, {0xc0002e9fc0, 0x1, 0x1}, {0xe82030, 0xc0002f6d70})
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:108 +0x3b7
main.newRunCmd.func1({0x0?, 0xc0000341a0?}, {0xc0002e9fc0?, 0x0?, 0x0?})
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:35 +0x30
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Run(0xc0002f4fd0?, {0xe79468?, 0x13b1200?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:247 +0x19d
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Run(0xc0002f4790?, {0xe79468?, 0x13b1200?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:251 +0x149
github.com/gnolang/gno/tm2/pkg/commands.(*Command).ParseAndRun(0xc0002f4b00?, {0xe79468, 0x13b1200}, {0xc000034190?, 0xc0002f4bb0?, 0xc0002f4c60?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:132 +0x49
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Execute(0xe82030?, {0xe79468?, 0x13b1200?}, {0xc000034190?, 0x13276c8?, 0xc0000061a0?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:114 +0x29
main.main()
	/home/howl/oc/gno/gnovm/cmd/gno/main.go:13 +0x5f
```

</p>
</details> 

Note: this is not about asserting on `nil` in general; I suspect there's as always the internal pesky difference between an "initialised" and an "uninitialised" value. This code works:

```go
package main

type ex int

func (ex) Error() string { return "" }

func main() {
	var i interface{}
	if _, ok := i.(ex); ok {
		println("wat")
	} else {
		println("ok")
	}
}

```

### PR DESCRIPTION
**Pull request by deelawn**
Fixes #1650 

This PR was originally intended to fix the case described in issue #1650, but it soon became apparent that there were other subtle inconsistencies between type assertions in go vs gno.  The changes outlined here attempt to fix the issues and the new file tests ensure correctness.  The summary below provides details as to the cases that were fixed for type assertions, both 1 and 2 -- 1 and 2 referring to the type assertion op codes, `OpTypeAssert1` and `OpTypeAssert2`.  The former handles type assertions with one LHS argument that panic on assertion failure and the latter handles those with two LHS arguments that assigns a boolean value dependent on success or failure.

### Summary of type assertion changes
- fail when the value being asserted has a nil type (i.e. the result of `recover()` when no panic has occurred). This applies for both cases where the type being asserted to is an interface or concrete type.
- fail when asserting to an interface type and the underlying type of the value being asserted is also an interface type (non-concrete type)

Also, is this an accurate assumption?
https://github.com/gnolang/gno/blob/7d4e8e645ca1d2e89f5a8f2e85470e66b3253b33/gnovm/pkg/gnolang/op_expressions.go#L261

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

File: gnovm/pkg/gnolang/op_expressions.go [hunk 1]
```diff
@@ -230,16 +255,22 @@ func (m *Machine) doOpTypeAssert1() {
...
 			if nxt, ok := xt.(*NativeType); ok {
-				impl = nxt.Type.Implements(nt.Type)
-			} else {
-				impl = false
+				// If the underlying native type is reflect.Interface kind, then this has no
+				// concrete value and should fail.
+				if nxt.Type.Kind() != reflect.Interface {
+					impl = nxt.Type.Implements(nt.Type)
+					nonConcrete = ""
+				}
```
Comment (thehowl) [inline gnovm/pkg/gnolang/op_expressions.go:266]: So, I don't think this assertion is fully correct and I would revert it to the previous one. Although... it's hard to think of any situation where this matters.

The situations where a `Type.Kind()` is an interface, but the value is actually concrete, are simply when the interface is "nested" within a type: https://go.dev/play/p/eKwnf3ncyti

So, it seems to me, that possibly one of the few places where this _could_ happen, is we tried to get `flag.Flag.Value`? I'm not entirely sure even then. We'd need an `interface{}` wrapped within some other kind of compound value

File: gnovm/pkg/gnolang/op_expressions.go [hunk 2]
```diff
@@ -204,16 +204,41 @@ func (m *Machine) doOpRef() {
...
+			if _, ok := baseOf(xt).(*InterfaceType); ok {
+				// TODO: default panic type?
+				ex := fmt.Sprintf(
+					"non-concrete %s doesn't implement %s",
+					xt.String(),
+					it.String())
+				m.Panic(typedString(ex))
+				return
+			}
+
```
[the remark this answers is not in the document]
Comment (deelawn) [reply gnovm/pkg/gnolang/op_expressions.go:238]: Yes there are. Like in go, there are untyped nil values and typed nil values. `xt == nil` evaluates to true when `xv` is an uptyped nil value; `xv.T` is nil. As far as I can tell, this can only happen two ways:
1) the value that is returned by `recover` if there is no panic to recover
2) below in the `doOpTypeAssert2` method when a type assertion fails -- `*xv = TypedValue{}`

So an example of a case where `t` is `*InterfaceType` and the underlying value (`xv`) is not nil is in the `type35a.gno` file test: https://github.com/gnolang/gno/blob/347db5de435cdf836e043e550c880d6d5b907858/gnovm/tests/files/type35a.gno

File: gnovm/pkg/gnolang/op_expressions.go (hunk 1 above)
Comment (deelawn) [reply gnovm/pkg/gnolang/op_expressions.go:266]: I don't quite understand all of that, but I agree that it is hard to think of situations where this matters. I think it matters for the sake of being consistent with the go spec.

The file test type37a_native.gno exemplifies how, in some cases, the type assertion should fail with native types, even if it is a typed nil value. For example, this should fail because there is no concrete value:
```go
var v interface{}
var r io.Reader
v = r
_ = r.(io.Reader)
```
This is the tricky part though the check `nxt.Type.Kind() != reflect.Interface` is just based on my observations that the type kind should be `reflect.Interface` is these cases where there is no concrete type.

And this type assertions succeeds:
```go
var v interface{}
var r io.Reader
r = bytes.NewBuffer([]byte("hello"))
v = r
_ = v.(io.Reader)
```

Let's chat offline to clear things up.

**Review by petar-dambovaliev — APPROVED** [review]

**Comment by ltzmaxwell** [comment]
Hey nice work. took a peek mostly good.
Please take a look at this one:

```go
package main

type ex int

func (ex) Error() string { return "" }

func main() {
	r := []int(nil)
	_, ok := r.(ex)
	println(ok)
}

// Output:
// false

// Go_Output:
// invalid operation: r (variable of type []int) is not an interface
```

the behavior the inconsistent with go. in this case, r has a static type of []int, so it actually can not be asserted to another concrete type.

**Comment by deelawn** [comment]
@ltzmaxwell so is it only the first case where the behavior is different between go and gno? The behavior of exampels 2 and 3 appear to be the same -- just the error messages are different.  I'll fix the first and look at the ease of changing these error messages to something more specific.

**Comment by deelawn** [comment]
@ltzmaxwell I've made changes to address your comments.  Let me know what you think.

File: gnovm/tests/file.go [hunk 3]
```diff
@@ -251,7 +251,22 @@ func RunFileTest(rootDir string, path string, opts ...RunFileTestOption) error {
...
 					}
-					if errstr != errWanted {
+
+					// Matching on long panic strings from the preprocessor can be hard/annoying. This allows support for a
+					// wildcard match for the entire string, prefix, suffix, or both.
+					matches := errstr == errWanted
+					if strings.Contains(errWanted, "*") {
+						if errWanted == "*" {
+							matches = true
+						} else if len(errWanted) > 1 && errWanted[0] == '*' && errWanted[len(errWanted)-1] == '*' {
```
Comment (ltzmaxwell) [inline gnovm/tests/file.go:261]: not fully get this. say where is this kind of errWanted from: (// `*`invalid operation: r<VPBlock(1,0)> (variable of type []int) is not an interface`*`)? is it manually pre-written before the test?

What I always do is to leave errWanted empty, and run the test to fill that part, (the mainly the logic in the else clause of if errWanted != "")

Comment (deelawn) [reply gnovm/tests/file.go:261]: Your comment makes me think of the "golden test" concept we have where you can run it to make the expected result equal to the run result. I'll check it out. In any case, this is normally set in the comment below the file test. It's just a pain to set the very long error string for preprocessor errors. Kind of like "I expect the error to contain this and I don't care about the rest."

Comment (ltzmaxwell) [reply gnovm/tests/file.go:261]: yes it's more about personal taste of mine, that don't want to set it manually to save time(maybe) and avoid potential mistake. 
So, it's not a problem here to me. except `*`...`*` is kinda wired, is it? haha.

Comment (deelawn) [reply gnovm/tests/file.go]: idk what i was thinking; i reverted it

**Review by ltzmaxwell — APPROVED** [review]

File: gnovm/pkg/gnolang/op_expressions.go [hunk 4]
```diff
@@ -204,16 +204,41 @@ func (m *Machine) doOpRef() {
...
+			m.Panic(typedString(ex))
+			return
+		}
+
 		if it, ok := baseOf(t).(*InterfaceType); ok {
+			// An interface type assertion on a value that doesn't have a concrete base
+			// type should always fail.
+			if _, ok := baseOf(xt).(*InterfaceType); ok {
+				// TODO: default panic type?
+				ex := fmt.Sprintf(
```
[the remark this answers is not in the document]
Comment (deelawn) [reply gnovm/pkg/gnolang/op_expressions.go:231]: Sure, I added it, but the error expected is a bit different `interface conversion: interface is nil, not main.Writer`

File: gnovm/pkg/gnolang/preprocess.go [hunk 5]
```diff
@@ -9,6 +9,8 @@ import (
 	"github.com/gnolang/gno/tm2/pkg/errors"
 )
 
+const blankIdentifer string = "_"
```
Comment (thehowl) [inline gnovm/pkg/gnolang/preprocess.go:12]: I agree on adding this, but can you do `s/"_"/blankIdentifier/g`?

**Review by thehowl — APPROVED** [review]

File: gnovm/pkg/gnolang/preprocess.go (hunk 5 above)
Comment (deelawn) [reply gnovm/pkg/gnolang/preprocess.go:12]: Will add this in a subsequent PR
