### PR TITLE
feat: implement `gno bug`

### LINKED ISSUE #733: Add `gno bug` subcommand
Let's create a tool like 'go bug' that checks for environment/context issues and generates markdown to simplify debugging.

Revise issue template and 'CONTRIBUTING.md'; add CI action to ensure master is always working.

### PR DESCRIPTION
**Pull request by harry-hov**
Contains initial implementation of `gno bug` command.

gno-bug

Closes #733 

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

File: gnovm/cmd/gno/bug.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+	}
+
+	var buf strings.Builder
+	buf.WriteString(bugHeader)
+	writeEnvironment(&buf)
+	buf.WriteString(bugFooter)
+	// TODO: include gno version or commit?
+
+	body := buf.String()
+	url := "https://github.com/gnolang/gno/issues/new?body=" + url.QueryEscape(body)
```
Comment (moul) [inline gnovm/cmd/gno/bug.go:43]: what happens when body is too long?

File: gnovm/cmd/gno/bug.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+	switch runtime.GOOS {
+	case "windows":
+		cmdArgs = []string{"cmd", "/c", "start"}
+	case "darwin":
+		cmdArgs = []string{"/usr/bin/open"}
+	default: // "linux"
+		cmdArgs = []string{"xdg-open"}
+	}
+
+	cmd := exec.Command(cmdArgs[0], append(cmdArgs[1:], url)...)
```
Comment (moul) [inline gnovm/cmd/gno/bug.go:85]:
```suggestion
	case "windows":
		cmdArgs = []string{"cmd", "/c", "start", url}
	case "darwin":
		cmdArgs = []string{"/usr/bin/open", url}
	default: // "linux"
		cmdArgs = []string{"xdg-open", url}
	}

	cmd := exec.Command(cmdArgs[0], cmdArgs[1:]...)
```

looks better to me.

File: gnovm/cmd/gno/bug.go (hunk 1 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go:43]: i don't think we need to worry about that here. Since `body` is not very dynamic. It will always be under 500chars. 
which is totally under the safe limit(2000chars?)?

Comment (harry-hov) [reply gnovm/cmd/gno/bug.go:43]: WDYT of this check? (if we are still worried about `body` being too long)
```go
if len(url) > 2048 {
    io.Println("Please file a new issue at github.com/gnolang/gno/issues/new using this template:")
    io.Println()
    io.Println(body)
}
```

File: gnovm/cmd/gno/bug_test.go [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+	tc := []testMainCase{
+		{
+			args:        []string{"bug -h"},
+			errShouldBe: "flag: help requested",
+		},
+		{
+			args:        []string{"bug unknown"},
+			errShouldBe: "flag: help requested",
+		},
+	}
```
Comment (moul) [inline gnovm/cmd/gno/bug_test.go:15]: It would be great to have at least one unit test that checks most of the things. Perhaps you can use regular expressions to verify the presence of important elements.

File: gnovm/cmd/gno/bug.go (hunk 1 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go:43]: Done b5673a11ecabfcc83980eac791903eec3f947881 ✅

File: gnovm/cmd/gno/bug_test.go (hunk 3 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug_test.go:15]: @moul:

I don't want it to open browser every time someone runs tests. I'm still confused about whats the best way to write tests for this command. 

> Perhaps you can use regular expressions to verify the presence of important elements.

Sorry, I did not get this part. Can you explain a bit more?

File: gnovm/cmd/gno/util.go [hunk 4]
```diff
@@ -343,3 +343,19 @@ func prettySize(nb int64) string {
 	}
 	return fmt.Sprintf("%.1f%c", float64(nb)/float64(div), "kMGTPE"[exp])
 }
+
+// isExecutionSuccessfulWithinTimeout checks if the execution of a given exec.Cmd
+// is successful within a specified timeout.
+func isExecutionSuccessfulWithinTimeout(cmd *exec.Cmd, timeout time.Duration) bool {
+	errc := make(chan error, 1)
+	go func() {
```
Comment (zivkovicmilos) [inline gnovm/cmd/gno/util.go:351]: This routine is never closed if the timeout triggers

File: gnovm/cmd/gno/bug_test.go [hunk 5]
```diff
@@ -0,0 +1,17 @@
+package main
```
Comment (zivkovicmilos) [inline gnovm/cmd/gno/bug_test.go:1]: Please add more unit tests for this gno bug functionality, I don't think checking that the help command works is a valid smoke test 🙏

File: gnovm/cmd/gno/util.go [hunk 6]
```diff
@@ -343,3 +343,19 @@ func prettySize(nb int64) string {
 	}
 	return fmt.Sprintf("%.1f%c", float64(nb)/float64(div), "kMGTPE"[exp])
 }
+
+// isExecutionSuccessfulWithinTimeout checks if the execution of a given exec.Cmd
+// is successful within a specified timeout.
+func isExecutionSuccessfulWithinTimeout(cmd *exec.Cmd, timeout time.Duration) bool {
```
Comment (zivkovicmilos) [inline gnovm/cmd/gno/util.go:349]: I'm on the fence about even having this method.

You only use it to verify the browser was opened -- why? I don't think the browser opening is contingent on this command working correctly. 

You can always print the issue body in the console, regardless if the browser opened or not

File: gnovm/cmd/gno/bug.go [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+}
+
+// writeGoVersion writes Go version information to the io.Writer.
+func writeGoVersion(w io.Writer) {
+	fmt.Fprintf(w, "$ go version\n")
+	fmt.Fprintf(w, "go version %s %s/%s\n\n", runtime.Version(), runtime.GOOS, runtime.GOARCH)
+}
+
+// writeOSDetails writes OS details (uses `uname`) to the io.Writer.
+func writeOSDetails(w io.Writer) {
```
Comment (zivkovicmilos) [inline gnovm/cmd/gno/bug.go:109]: I don't think you need this method at all, what additional info does `uname -sr` give you?

File: gnovm/cmd/gno/bug.go [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+func writeEnvironment(w io.Writer) {
+	fmt.Fprintf(w, "### Environment\n\n")
+	fmt.Fprintf(w, "```\n")
+	writeGoVersion(w)
+	writeOSDetails(w)
+	fmt.Fprintf(w, "```\n\n")
+}
+
+// writeGoVersion writes Go version information to the io.Writer.
+func writeGoVersion(w io.Writer) {
```
Comment (zivkovicmilos) [inline gnovm/cmd/gno/bug.go:103]: Why not just use `runtime.Version()`? https://pkg.go.dev/runtime#Version

**Review by zivkovicmilos — CHANGES_REQUESTED** [review]
I've left comments that need to be addressed before we proceed.

Please take a look 🙏

File: gnovm/cmd/gno/bug.go (hunk 7 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go]: Removed

File: gnovm/cmd/gno/bug.go (hunk 8 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go]: Done

File: gnovm/cmd/gno/util.go (hunk 6 above)
Comment (harry-hov) [reply gnovm/cmd/gno/util.go]: Removed.

File: gnovm/cmd/gno/util.go (hunk 4 above)
Comment (harry-hov) [reply gnovm/cmd/gno/util.go]: Removed

File: gnovm/cmd/gno/bug.go [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+	cmd := exec.Command(cmdArgs[0], cmdArgs[1:]...)
+	if cmd.Start() == nil && isExecutionSuccessfulWithinTimeout(cmd, 3*time.Second) {
+		return true
+	}
+	return false
+}
+
+// writeEnvironment writes environment information to the provided io.Writer.
+// It includes Go version details and OS details within code blocks.
+func writeEnvironment(w io.Writer) {
```
[the remark this answers is not in the document]
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go]: Done

File: gnovm/cmd/gno/bug.go [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+const bugTmpl = `## [Subject of the issue]
+
+### Description
+
+Describe your issue in as much detail as possible here
+
+### Your environment
+
+* go version {{.GoVersion}} {{.Os}}/{{.Arch}}
+* version of gno
```
Comment (thehowl) [inline gnovm/cmd/gno/bug.go:24]: can we somehow get this information with `debug.BuildInfo`? https://pkg.go.dev/runtime/debug#BuildInfo

otherwise we do it the good ol' way and put the version as a [compile-time injected variable](https://blog.alexellis.io/inject-build-time-vars-golang/) when running `make build` / install.

File: gnovm/cmd/gno/main.go [hunk 11]
```diff
@@ -41,8 +42,7 @@ func newGnocliCmd(io commands.IO) *commands.Command {
 		// publish/release
 		// generate
 		// "vm" -- starts an in-memory chain that can be interacted with?
-		// bug -- start a bug report
-		// version -- show gno, golang versions
+		// version -- show gnodev, golang versions
```
Comment (thehowl) [inline gnovm/cmd/gno/main.go:45]:
```suggestion
		// version -- show cmd/gno, golang versions
```

(let's put cmd/ to specify that we're talking about the binary)

File: gnovm/cmd/gno/bug.go [hunk 12]
```diff
@@ -0,0 +1,129 @@
...
+	"net/url"
+	"os/exec"
+	"runtime"
+	"strings"
+	"text/template"
+
+	"github.com/gnolang/gno/tm2/pkg/commands"
+)
+
+const bugTmpl = `## [Subject of the issue]
```
Comment (thehowl) [inline gnovm/cmd/gno/bug.go:15]:
```suggestion
// NOTE: keep in sync with .github/ISSUE_TEMPLATE/BUG-REPORT.md
const bugTmpl = `## [Subject of the issue]
```

Comment (thehowl) [reply gnovm/cmd/gno/bug.go:15]: + modify the file, place a note in the front matter (using a yaml comment)

```yaml
# NOTE: keep in sync with gnovm/cmd/gno/bug.go
```

File: gnovm/cmd/gno/bug.go [hunk 13]
```diff
@@ -0,0 +1,129 @@
...
+		cmdArgs = []string{"cmd", "/c", "start", url}
+	case "darwin":
+		cmdArgs = []string{"/usr/bin/open", url}
+	default: // "linux"
+		cmdArgs = []string{"xdg-open", url}
+	}
+
+	cmd := exec.Command(cmdArgs[0], cmdArgs[1:]...)
+	return cmd.Start()
+}
```
Comment (thehowl) [inline gnovm/cmd/gno/bug.go:129]: I did a bit of research. This should work well enough, but there are two other approaches we may take:

- [the go repo's approach](https://github.com/golang/go/blob/b6ca586181f3f1531c01d51d632b50b2c7c784ba/src/cmd/internal/browser/browser.go#L15-L50), which also works if you don't have xdg-open for whatever reason.
- https://github.com/pkg/browser, third party dependency, great cross-platform and windows support.

Just for reference, I don't feel strongly towards any of these and this also works fine, just putting it out there.

File: gnovm/cmd/gno/bug.go [hunk 14]
```diff
@@ -0,0 +1,129 @@
...
+		return err
+	}
+	tmpl.Execute(&buf, bugReportEnv)
+
+	body := buf.String()
+	url := "https://github.com/gnolang/gno/issues/new?body=" + url.QueryEscape(body)
+
+	if !cfg.skipBrowser {
+		// Try opening browser (ignore error)
+		_ = openBrowser(url)
```
Comment (thehowl) [inline gnovm/cmd/gno/bug.go:104]: mhhh. don't print the template if opening browser succeeds?

**Review by thehowl — APPROVED** [review]
nits

File: gnovm/cmd/gno/bug.go (hunk 14 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go:104]: i just did the opposite 🤷‍♂️

https://github.com/gnolang/gno/pull/1325#discussion_r1388140728
> ...
> You can always print the issue body in the console, regardless if the browser opened or not

File: gnovm/cmd/gno/bug.go (hunk 12 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go:16]: Should be resolved by: https://github.com/gnolang/gno/pull/1325/commits/5e655b8e9637815987eba0ffbca7be6250af7dfa

File: gnovm/cmd/gno/bug.go (hunk 10 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go:25]: > can we somehow get this information with debug.BuildInfo? https://pkg.go.dev/runtime/debug#BuildInfo

From my understanding of `debug.BuildInfo`, I'm not entirely sure if there's a way.

> otherwise we do it the good ol' way and put the version as a [compile-time injected variable](https://blog.alexellis.io/inject-build-time-vars-golang/) when running make build / install.

I like this idea. In fact, I was already thinking about it. Later, I decided to work on `gno version` instead.

already added as TODO  here -> https://github.com/gnolang/gno/pull/1325/files#diff-2ba8fa8e90302c604c98727b5c82205ad57c1952fda669f9b06db798930fb6d4R85

Comment (thehowl) [reply gnovm/cmd/gno/bug.go:25]: :+1: 

I've taken a look at BuildInfo; I think that by extracting module information, we could get the commit being used; but I didn't delve too much into it. Maybe try playing around with it before committing to the compile-time injected variable, as BuildInfo has the advantage of working even with `go build` and `go install`. :+1: for doing this in another PR, though.

Comment (harry-hov) [reply gnovm/cmd/gno/bug.go]: Didn't know that. Thanks for the info. 

Done: 802139e6a55038b25361e5c1b78206e42aa92f0c

File: gnovm/cmd/gno/bug.go (hunk 14 above)
Comment (harry-hov) [reply gnovm/cmd/gno/bug.go]: Done: eb277078e1cf1f040e869b36c11fd45ae4c9bbe3

**Review by thehowl — APPROVED** [review]
