### PR TITLE
fix: bit shifting const expr overflow

### LINKED ISSUE #3128: Undetected overflow in constant expression
## Description

The following constant declaration should fail due to int32 overflow but it does not:

```go
const a = int32(1) << 33
```

### PR DESCRIPTION
**Pull request by petar-dambovaliev**
This provides validation for cases where bit shifting const expressions overflow.

Closes #3128

### CODE REVIEW

File: gnovm/pkg/gnolang/op_binary.go [hunk 1]
```diff
@@ -1196,32 +1197,116 @@ func xorAssign(lv, rv *TypedValue) {
 }
 
 // for doOpShl and doOpShlAssign.
-func shlAssign(lv, rv *TypedValue) {
+func shlAssign(m *Machine, lv, rv *TypedValue) {
 	rv.AssertNonNegative("runtime error: negative shift amount")
+
+	validateSize := func(v func() bool) {
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/op_binary.go:1203]: please change this name also

File: gnovm/pkg/gnolang/machine.go [hunk 2]
```diff
@@ -169,7 +169,7 @@ func NewMachineWithOptions(opts MachineOptions) *Machine {
 	mm := machinePool.Get().(*Machine)
 	mm.Package = pv
 	mm.Alloc = alloc
-	mm.CheckTypes = checkTypes
+	mm.PreprocessorMode = checkTypes
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/machine.go:172]: why not just  mm.PreprocessorMode = opts.PreprocessorMode

**Review by ltzmaxwell — APPROVED** [review]
LGTM
