### PR TITLE
fix(gnovm): allow multiple NaN keys in map

### LINKED ISSUE #3867: maps cannot contain multiple NaN's
This is behaviour that also surprised me about Go that I did not know about, but apparently, because `NaN != NaN`, then you can have multiple NaN's as keys in a single map.

In Gno, this leads to a panic due to having duplicate keys.

```
package main

import (
	"fmt"
	"math"
)

var NaN = math.NaN()

func main() {
	fmt.Println(map[float64]int{NaN: 1, NaN: 2})
}
```

### PR DESCRIPTION
**Pull request by thehowl**
This PR fixes #3867. It's an alternative to #3932. Depends on #4327.

- [As Jae requested,](https://github.com/gnolang/gno/pull/4114#issuecomment-3043155234) ComputeMapKey now returns a second value indicating whether a NaN is contained in the map key, and as such the map key is != to all others.
- Negative 0 is now also normalized to `0`, matching go's behaviour.
- Map keys are now re-assigned when using `GetPointerForKey` on an existing key, in order to match [Go's behaviour](https://go.dev/play/p/iNPDR4FQlRv).
- It detects NaN using the `softfloat` package, rather than using hardware FP instructions, ensuring cross-architecture determinism.

This PR doesn't strictly depend on #4327, also because instead of copying the key in `GetPointerForKey` we copy it in its users, allowing to call `DidUpdate` on the copied key as necessary, however it does work from the same "fix".

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: thehowl/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

**Comment by thehowl** [comment]
There is a possible problem: this behaves differently in Go and Gno...

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"math"
)

func main() {
	n0 := math.Float64frombits(1 << 63)
	fmt.Println(n0)
	m := map[float64]string{}
	m[0] = "hey"
	m[n0] = "world"
	fmt.Println(m)
}

// Output:
// -0
// map[0:world]
```

In Go, the key that is used is actually the last: https://go.dev/play/p/K--afH1wh0L -- so the result is `map[-0:world]`.

**Comment by thehowl** [comment]
ALSO realised this doesn't work for ie. a struct with a float... we probably still need some modification to ComputeMapKey

**Review by mvertes — APPROVED** [review]
Looks good to me

**Comment by jaekwon** [comment]
Since you can't delete a NaN key I presume, couldn't we solve this with minimal changes?
There's already a List, so the insertion order is what would make it deterministic?

like
```diff
diff --git a/gnovm/pkg/gnolang/values.go b/gnovm/pkg/gnolang/values.go
index 04c0ce916..a4fc3b529 100644
--- a/gnovm/pkg/gnolang/values.go
+++ b/gnovm/pkg/gnolang/values.go
@@ -723,6 +723,7 @@ func (mv *MapValue) GetLength() int {
 // GetPointerForKey is only used for assignment, so the key
 // is not returned as part of the pointer, and TV is not filled.
 func (mv *MapValue) GetPointerForKey(alloc *Allocator, store Store, key *TypedValue) PointerValue {
+       // If NaN, instead of computing map key, just append to List.
        kmk := key.ComputeMapKey(store, false)
        if mli, ok := mv.vmap[kmk]; ok {
                return PointerValue{
@@ -743,6 +744,7 @@ func (mv *MapValue) GetPointerForKey(alloc *Allocator, store Store, key *TypedVa
 // Like GetPointerForKey, but does not create a slot if key
 // doesn't exist.
 func (mv *MapValue) GetValueForKey(store Store, key *TypedValue) (val TypedValue, ok bool) {
+       // If key is NaN, return default
        kmk := key.ComputeMapKey(store, false)
        if mli, exists := mv.vmap[kmk]; exists {
                fillValueTV(store, &mli.Value)
@@ -752,6 +754,7 @@ func (mv *MapValue) GetValueForKey(store Store, key *TypedValue) (val TypedValue
 }
 
 func (mv *MapValue) DeleteForKey(store Store, key *TypedValue) {
+       // if key is NaN, do nothing.
        kmk := key.ComputeMapKey(store, false)
        if mli, ok := mv.vmap[kmk]; ok {
                mv.List.Remove(mli)
```

**Comment by thehowl** [comment]
I replied to this review on Signal a while back, cross-posting here:

image


<details><summary>Text-based version, for searchability</summary>
<p>


> The idea behind the PR was to follow in the footsteps of what Marc did, which I think largely makes sense
> 
> And that is not to change the code path, ie. adding conditionals or slowing down code anyway, for the 99.9999% of cases that don't have NaNs
> 
> Also keep in mind any solution has to work not just for map[float64]V, but also for map[struct{k float64}]V
> 
> So you need a "deep" nan check for those cases, which is potentially expensive for large structs.
> You can make this cheaper by returning a second param in ComputeMapKey, but again, this makes code more complex to account for the 1/1000000th case where there is a nan
> 
> because then you need to add a check for the second param each time

</p>
</details>

File: gnovm/pkg/gnolang/values.go [hunk 1]
```diff
@@ -725,6 +727,11 @@ func (mv *MapValue) GetLength() int {
 func (mv *MapValue) GetPointerForKey(alloc *Allocator, store Store, key *TypedValue) PointerValue {
 	kmk := key.ComputeMapKey(store, false)
 	if mli, ok := mv.vmap[kmk]; ok {
+		key2 := key.Copy(alloc)
+		// When assigning to a map item, the key is always equal to that of the
+		// last assignment; this is mostly noticeable in the case of -0 / 0:
+		// https://go.dev/play/p/iNPDR4FQlRv
+		mli.Key = key2
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go]: i don't see why mli needs to be modified here.

File: gnovm/pkg/gnolang/values.go [hunk 2]
```diff
@@ -1052,64 +1072,76 @@ func (tv TypedValue) unrefCopy(alloc *Allocator, store Store) (cp TypedValue) {
...
+		byte(i>>24),
+		byte(i>>32),
+		byte(i>>40),
+		byte(i>>48))
+}
+
 // Returns encoded bytes for primitive values.
-// These bytes are used for both value hashes as well
-// as hash key bytes.
-func (tv *TypedValue) PrimitiveBytes() (data []byte) {
```
Comment (jaekwon) [inline gnovm/pkg/gnolang/values.go:1069]: want to keep this function as is for other uses... i see the benefit of passing in the bz tho.

**Comment by jaekwon** [comment]
> ```diff
> // If NaN, instead of computing map key, just append to List.
> ```

Thanks, that makes sense. 
Having ComputeMapKey return a second bool isn't bad, see below:
The benefit of this is that it's clear that anything with NaN doesn't have a map key.
It's *slightly* slower than otherwise, but map operations are slow anyways so it's negligible.
And your optimization of passing in bz can still be utilized, but would rather
have it on top of the following... 

(I like your solution, but really, the slowdown here is neglibible compared to map operations already!
so why not go for the more perfect solution without mental overhead? 
imagine somebody having to understand the nanCounter vs seeing
ComputeMapKey return false.) 

```go
diff --git a/gnovm/pkg/gnolang/realm.go b/gnovm/pkg/gnolang/realm.go
index 4f1626a66..71429c726 100644
--- a/gnovm/pkg/gnolang/realm.go
+++ b/gnovm/pkg/gnolang/realm.go
@@ -1434,8 +1434,10 @@ func fillTypesOfValue(store Store, val Value) Value {
 		for cur := cv.List.Head; cur != nil; cur = cur.Next {
 			fillTypesTV(store, &cur.Key)
 			fillTypesTV(store, &cur.Value)
-
-			cv.vmap[cur.Key.ComputeMapKey(store, false)] = cur
+			mkey, nan := cur.Key.ComputeMapKey(store, false)
+			if !nan {
+				cv.vmap[mkey] = cur
+			}
 		}
 		return cv
 	case TypeValue:
diff --git a/gnovm/pkg/gnolang/values.go b/gnovm/pkg/gnolang/values.go
index a4fc3b529..73be21ceb 100644
--- a/gnovm/pkg/gnolang/values.go
+++ b/gnovm/pkg/gnolang/values.go
@@ -724,7 +724,8 @@ func (mv *MapValue) GetLength() int {
 // is not returned as part of the pointer, and TV is not filled.
 func (mv *MapValue) GetPointerForKey(alloc *Allocator, store Store, key *TypedValue) PointerValue {
 	// If NaN, instead of computing map key, just append to List.
-	kmk := key.ComputeMapKey(store, false)
+	kmk, nan := key.ComputeMapKey(store, false)
+	if !nan {
 	if mli, ok := mv.vmap[kmk]; ok {
 		return PointerValue{
 			TV:    fillValueTV(store, &mli.Value),
@@ -732,6 +733,7 @@ func (mv *MapValue) GetPointerForKey(alloc *Allocator, store Store, key *TypedVa
 			Index: PointerIndexMap,
 		}
 	}
+	}
 	mli := mv.List.Append(alloc, *key)
 	mv.vmap[kmk] = mli
 	return PointerValue{
@@ -745,7 +747,7 @@ func (mv *MapValue) GetPointerForKey(alloc *Allocator, store Store, key *TypedVa
 // doesn't exist.
 func (mv *MapValue) GetValueForKey(store Store, key *TypedValue) (val TypedValue, ok bool) {
 	// If key is NaN, return default
-	kmk := key.ComputeMapKey(store, false)
+	kmk, nan := key.ComputeMapKey(store, false)
 	if mli, exists := mv.vmap[kmk]; exists {
 		fillValueTV(store, &mli.Value)
 		val, ok = mli.Value, true
@@ -755,7 +757,7 @@ func (mv *MapValue) GetValueForKey(store Store, key *TypedValue) (val TypedValue
 
 func (mv *MapValue) DeleteForKey(store Store, key *TypedValue) {
 	// if key is NaN, do nothing.
-	kmk := key.ComputeMapKey(store, false)
+	kmk, nan := key.ComputeMapKey(store, false)
 	if mli, ok := mv.vmap[kmk]; ok {
 		mv.List.Remove(mli)
 		delete(mv.vmap, kmk)
@@ -990,6 +992,19 @@ func (tv *TypedValue) IsNilInterface() bool {
 	return false
 }
 
+func (tv *TypedValue) IsNaN() bool {
+	switch tv.T.Kind() {
+	case Float32Kind:
+		_, _, _, _, nan := softfloat.Funpack32(tv.GetFloat32())
+		return nan
+	case Float64Kind:
+		_, _, _, _, nan := softfloat.Funpack64(tv.GetFloat64())
+		return nan
+	default:
+		return false
+	}
+}
+
 func (tv *TypedValue) HasKind(k Kind) bool {
 	if tv.T == nil {
 		return false
@@ -1520,7 +1535,7 @@ func (tv *TypedValue) AssertNonNegative(msg string) {
 	}
 }
 
-func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
+func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) (mkey MapKey, nan bool){
 	// Special case when nil: has no separator.
 	if tv.T == nil {
 		if debug {
@@ -1528,7 +1543,7 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
 				panic("should not happen")
 			}
 		}
-		return MapKey(nilStr)
+		return MapKey(nilStr), false
 	}
 	// General case.
 	bz := make([]byte, 0, 64)
@@ -1538,6 +1553,9 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
 	}
 	switch bt := baseOf(tv.T).(type) {
 	case PrimitiveType:
+		if tv.IsNaN() {
+			return MapKey{}, true
+		}
 		pbz := tv.PrimitiveBytes()
 		bz = append(bz, pbz...)
 	case *PointerType:
@@ -1554,7 +1572,11 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
 			omitTypes := bt.Elem().Kind() != InterfaceKind
 			for i := range al {
 				ev := fillValueTV(store, &av.List[i])
-				bz = append(bz, ev.ComputeMapKey(store, omitTypes)...)
+				mkey, nan := ev.ComputeMapKey(store, omitTypes)
+				if nan {
+					return MapKey{}, true
+				}
+				bz = append(bz, mkey...)
 				if i != al-1 {
 					bz = append(bz, ',')
 				}
@@ -1572,7 +1594,11 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
 		for i := range sl {
 			fv := fillValueTV(store, &sv.Fields[i])
 			omitTypes := bt.Fields[i].Type.Kind() != InterfaceKind
-			bz = append(bz, fv.ComputeMapKey(store, omitTypes)...)
+			mkey, nan := fv.ComputeMapKey(store, omitTypes)
+			if nan {
+				return MapKey{}, true
+			}
+			bz = append(bz, mkey...)
 			if i != sl-1 {
 				bz = append(bz, ',')
 			}
@@ -1594,7 +1620,7 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
 			"unexpected map key type %s",
 			tv.T.String()))
 	}
-	return MapKey(bz)
+	return MapKey(bz), false
 }
 
 // ----------------------------------------

```

File: gnovm/pkg/gnolang/values.go (hunk 1 above)
Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/values.go]: cross reference: https://github.com/gnolang/gno/pull/4327

Comment (thehowl) [reply gnovm/pkg/gnolang/values.go]: See the [go playground link in the comment](https://go.dev/play/p/iNPDR4FQlRv). Without this addition, in Gno the value would stay always the same as that of the first assignment. This addition makes Gno's behaviour consistent with Go's.

File: gnovm/pkg/gnolang/values.go (hunk 2 above)
Comment (thehowl) [reply gnovm/pkg/gnolang/values.go:1058]: There are no other uses at present. We can always add it back when necessary.

**Comment by thehowl** [comment]
@ltzmaxwell I updated some of the code you added recently (#4385) in light of [this comment](https://github.com/gnolang/gno/pull/4114#discussion_r2221736827), let me know if it sounds good to you.

@jaekwon, this now returns a second parameter as you mentioned; please take a look.

File: gnovm/pkg/gnolang/values.go [hunk 3]
```diff
@@ -1950,10 +1990,13 @@ func (tv *TypedValue) GetPointerAtIndex(rlm *Realm, alloc *Allocator, store Stor
...
-		key := iv.ComputeMapKey(store, false)
-		if _, ok := mv.vmap[key]; ok {
-			exist = true
+		var oldObject Object
+		key, isNaN := iv.ComputeMapKey(store, false)
+		if !isNaN {
+			k, ok := mv.vmap[key]
+			if ok {
+				oldObject = k.Key.GetFirstObject(store)
+			}
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go]: i think the idea here is for some specific situation, like S{0, -0} and S{-0,0}, they are different object but computed as same mapkey, thus still needed to be attached?

File: gnovm/pkg/gnolang/values.go [hunk 4]
```diff
@@ -724,12 +725,19 @@ func (mv *MapValue) GetLength() int {
...
-	kmk := key.ComputeMapKey(store, false)
-	if mli, ok := mv.vmap[kmk]; ok {
-		return PointerValue{
-			TV:    fillValueTV(store, &mli.Value),
-			Base:  mv,
-			Index: PointerIndexMap,
+	kmk, isNaN := key.ComputeMapKey(store, false)
+	if !isNaN {
+		if mli, ok := mv.vmap[kmk]; ok {
+			key2 := key.Copy(alloc)
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go]: can you please check this PR: https://github.com/gnolang/gno/pull/4327. 
it looks `key` should always be copied?

File: gnovm/pkg/gnolang/values.go (hunk 3 above)
Comment (thehowl) [reply gnovm/pkg/gnolang/values.go]: exactly; it follows from the other change in the realm logic.

Updating the comment

File: gnovm/pkg/gnolang/values.go (hunk 4 above)
Comment (thehowl) [reply gnovm/pkg/gnolang/values.go:731]: Okay, sounds good. I'll apply that change here with you as co-author.

**Comment by thehowl** [comment]
I addressed maxwell's review, and updated the OP to match the changed method.

I suggest we merge #4327 first, and then go ahead and merge this - @ltzmaxwell, in the meantime, if you could have a second look and tell me if the changes are sensible ;)

File: gnovm/pkg/gnolang/values.go [hunk 5]
```diff
@@ -1546,8 +1551,34 @@ func (tv *TypedValue) ComputeMapKey(store Store, omitType bool) MapKey {
...
 	switch bt := baseOf(tv.T).(type) {
 	case PrimitiveType:
-		pbz := tv.PrimitiveBytes()
-		bz = append(bz, pbz...)
+		const (
+			fourZeroes  = "\x00\x00\x00\x00"
+			eightZeroes = fourZeroes + fourZeroes
+		)
+		// For float types, return isNaN = true if there is a nan value,
+		// normalize to 0 if negative zero.
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/values.go:1559]:
```suggestion
		// normalize to 0 if negative zero, so that 0.0 and -0.0 are treated as same key.
```

Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/values.go:1559]: do you think it's better?
