### PR TITLE
fix(gnovm): handle non call expression valuedecl values

### LINKED ISSUE #2636: Panic on Type Assertion with Interface
## Description:
**Issue Summary:**

A panic occurs when performing a type assertion on an `interface{}` in Gnolang. The following code works as expected in Go (Golang), but in Gnolang, it results in a runtime panic:

```go
package main

import "fmt"

func main() {
	var i interface{} = 1
	var a, ok = i.(int)
	fmt.Println(a, ok)
}
```

**Expected Behavior:**

The code should execute without panic, correctly performing the type assertion. The expected output should be:

```
1 true
```

**Actual Behavior:**

In Gnolang, running the above code causes a panic with the message:

```
panic: interface conversion: gnolang.Expr is *gnolang.TypeAssertExpr, not *gnolang.CallExpr
```

This suggests an issue with how type assertions are being handled internally, specifically when converting types within the interface.

### PR DESCRIPTION
**Pull request by deelawn**
Closes #2636.

With a value declaration like `var a, b = ...`, we currently only support a call expression on the RHS. This PR supports type assertion and index expressions as well.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Review by thehowl — APPROVED** [review]
ok; i still think the problem is that we should not have different code for AssignStmt.DECL and DeclStmt. but it's fine to fix the issue directly.

File: gnovm/pkg/gnolang/preprocess.go [hunk 1]
```diff
@@ -2163,12 +2163,38 @@ func Preprocess(store Store, ctx BlockNode, n Node) Node {
...
+						expr.(*IndexExpr).HasOK = true
+					default:
+						panic(fmt.Sprintf("unexpected ValueDecl value expression type %T", expr))
+					}
+
+					if rLen := len(tuple.Elts); rLen != numNames {
+						rhsExprString := valueExpr.String()
+						if cx, ok := valueExpr.(*CallExpr); ok {
+							rhsExprString = cx.Func.String()
+						}
```
Comment (ltzmaxwell) [inline gnovm/pkg/gnolang/preprocess.go:2195]: do we need this? seems `valueExpr.String()` is already good.

**Review by ltzmaxwell — APPROVED** [review]

File: gnovm/pkg/gnolang/preprocess.go (hunk 1 above)
Comment (deelawn) [reply gnovm/pkg/gnolang/preprocess.go:2195]: This is just to keep it consistent with how this was working previously for call expressions -- CallExpr.String() does not return the same thing as CallExpr.Func.String().

**Review by piux2 — APPROVED** [review]
LGTM, Thank you!

File: gnovm/pkg/gnolang/preprocess.go (hunk 1 above)
Comment (ltzmaxwell) [reply gnovm/pkg/gnolang/preprocess.go:2195]: The difference between these two outputs is very small. If there aren't many side effects, I believe using one `valueExpr.String()` is better.
