### PR TITLE
chore(vm): fix a crash when requesting a missing file

### LINKED ISSUE #171: Crash when requesting for a missing file
To reproduce request a missing file in `gnoland` through web-interface: https://gno.land/r/boards/missing.txt:
```
RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference
```

Meanwhile, the `gnoland` node reports a crash:

```
.level 2 .msg Panic in RPC HTTP handler [err runtime error: invalid memory address or nil pointer dereference stack goroutine 26 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/gnolang/gno/pkgs/bft/rpc/lib/server.RecoverAndLogHandler.func1.1()
        /home/jubnzv/Dev/gno/pkgs/bft/rpc/lib/server/http_server.go:161 +0x18f
panic({0xb876a0, 0x1354380})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/gnolang/gno/pkgs/sdk/vm.(*VMKeeper).QueryFile(0xe9b120?, {{0xea6170, 0xc000040178}, 0x0, {0xea5e08, 0xc00412a520}, {0xea6368, 0xc007394580}, {0xc000330420, 0x9}, ...}, ...)
        /home/jubnzv/Dev/gno/pkgs/sdk/vm/keeper.go:412 +0xe8
github.com/gnolang/gno/pkgs/sdk/vm.vmHandler.queryFile({_}, {{0xea6170, 0xc000040178}, 0x0, {0xea5e08, 0xc00412a520}, {0xea6368, 0xc007394580}, {0xc000330420, 0x9}, ...}, ...)
        /home/jubnzv/Dev/gno/pkgs/sdk/vm/handler.go:187 +0xe6
github.com/gnolang/gno/pkgs/sdk/vm.vmHandler.Query({_}, {{0xea6170, 0xc000040178}, 0x0, {0xea5e08, 0xc00412a520}, {0xea6368, 0xc007394580}, {0xc000330420, 0x9}, ...}, ...)
        /home/jubnzv/Dev/gno/pkgs/sdk/vm/handler.go:106 +0x219
github.com/gnolang/gno/pkgs/sdk.handleQueryCustom(0xc0000fe000, {0xc0068f0220, 0x0?, _}, {{}, {0xc007086080, 0x1d, 0x1e}, {0xc006f4e298, 0x8}, ...})
        /home/jubnzv/Dev/gno/pkgs/sdk/baseapp.go:494 +0x518
github.com/gnolang/gno/pkgs/sdk.(*BaseApp).Query(0xc003a70410?, {{}, {0xc007086080, 0x1d, 0x1e}, {0xc006f4e298, 0x8}, 0x0, 0x0})
        /home/jubnzv/Dev/gno/pkgs/sdk/baseapp.go:392 +0x28f
github.com/gnolang/gno/pkgs/bft/abci/client.(*localClient).QuerySync(0xc00412a430?, {{}, {0xc007086080, 0x1d, 0x1e}, {0xc006f4e298, 0x8}, 0x0, 0x0})
        /home/jubnzv/Dev/gno/pkgs/bft/abci/client/local_client.go:180 +0x158
github.com/gnolang/gno/pkgs/bft/proxy.(*appConnQuery).QuerySync(0x0?, {{}, {0xc007086080, 0x1d, 0x1e}, {0xc006f4e298, 0x8}, 0x0, 0x0})
        /home/jubnzv/Dev/gno/pkgs/bft/proxy/app_conn.go:143 +0xfc
github.com/gnolang/gno/pkgs/bft/rpc/core.ABCIQuery(0x8?, {0xc006f4e298, 0x8}, {0xc007086080, 0x1d, 0x1e}, 0x2?, 0xb9?)
        /home/jubnzv/Dev/gno/pkgs/bft/rpc/core/abci.go:55 +0x12f
reflect.Value.call({0xb94b80?, 0xdcaf68?, 0x80?}, {0xc56f84, 0x4}, {0xc001a6a600, 0x5, 0x18?})
        /usr/lib/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xb94b80?, 0xdcaf68?, 0x60?}, {0xc001a6a600, 0x5, 0x5})
        /usr/lib/go/src/reflect/value.go:339 +0xbf
github.com/gnolang/gno/pkgs/bft/rpc/lib/server.makeJSONRPCHandler.func1({0xea4d58, 0xc006f94150}, 0xc009d6db00)
        /home/jubnzv/Dev/gno/pkgs/bft/rpc/lib/server/handlers.go:158 +0xe0e
github.com/gnolang/gno/pkgs/bft/rpc/lib/server.handleInvalidJSONRPCPaths.func1({0xea4d58?, 0xc006f94150?}, 0x7fd2a7636108?)
        /home/jubnzv/Dev/gno/pkgs/bft/rpc/lib/server/handlers.go:182 +0x5d
net/http.HandlerFunc.ServeHTTP(0xc003fda800?, {0xea4d58?, 0xc006f94150?}, 0xc0073838a0?)
        /usr/lib/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x160?, {0xea4d58, 0xc006f94150}, 0xc009d6db00)
        /usr/lib/go/src/net/http/server.go:2462 +0x149
github.com/gnolang/gno/pkgs/bft/rpc/lib/server.maxBytesHandler.ServeHTTP({{0xea10e0?, 0xc003fc7a40?}, 0x40f387?}, {0xea4d58?, 0xc006f94150}, 0xc009d6db00)
        /home/jubnzv/Dev/gno/pkgs/bft/rpc/lib/server/http_server.go:206 +0x122
github.com/gnolang/gno/pkgs/bft/rpc/lib/server.RecoverAndLogHandler.func1({0xea5bc8?, 0xc00a10a0e0}, 0xc009d6db00)
        /home/jubnzv/Dev/gno/pkgs/bft/rpc/lib/server/http_server.go:179 +0x326
net/http.HandlerFunc.ServeHTTP(0x0?, {0xea5bc8?, 0xc00a10a0e0?}, 0x40f025?)
        /usr/lib/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0xea3f28?}, {0xea5bc8, 0xc00a10a0e0}, 0xc009d6db00)
        /usr/lib/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0016088c0, {0xea61e0, 0xc00a6fa270})
        /usr/lib/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3071 +0x4db
 [module rpc-server]]
```

### PR DESCRIPTION
**Pull request by jubnzv**
We could test it using the web-interface. Open a file: https://gno.land/r/boards/missing.txt (or http://127.0.0.1:8888/r/boards/missing.txt on a local node).

Before:

```
RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference
```

After:

```
file gno.land/r/boards/missing.txt is not available
```

Closes #171

### CODE REVIEW

File: pkgs/sdk/vm/keeper.go [hunk 1]
```diff
@@ -406,6 +406,9 @@ func (vm *VMKeeper) QueryFile(ctx sdk.Context, filepath string) (res string, err
 	dirpath, filename := std.SplitFilepath(filepath)
 	if filename != "" {
 		memFile := store.GetMemFile(dirpath, filename)
+		if memFile == nil {
+			return "", fmt.Errorf("file %s is not available", filepath)
```
Comment (moul) [inline pkgs/sdk/vm/keeper.go:410]:
```suggestion
			return "", fmt.Errorf("file %q is not available", filepath) // TODO: XSS protection
```

It will quotes the string + comment about taking care of XSS in the future

**Review by moul — CHANGES_REQUESTED** [review]

**Review by moul — APPROVED** [review]
