### PR TITLE
fix: In getLedgerDevice() error, mention CGO_ENABLED=1

### LINKED ISSUE #2737: [gnokey] Ledger device not found
## Description

Using a Ledger Nano S, with the installed Cosmos app (v2.35.24), and having installed `gnokey` from master at commit `651f5aac3706f55aa33da06a1185fe9508cb3ec2`, the following error is presented when trying to add a key from the ledger device to the `gnokey` keybase:

```bash
> gnokey add ledger myledgerkey
unable to create Ledger reference in keybase, LedgerHID device (idx 0) not found. Ledger LOCKED OR Other Program/Web Browser may have control of device.
```
The device is unlocked, not used by anything else, and the Cosmos app is open. This happens when `gnokey` is either installed with `go install`, or built with `go build` and ran as a binary.

As @zivkovicmilos pointed out, the only way to get this functionality to work currently is by directly doing `go run` on the gnokey suite, ie from the `gno/gno.land/cmd/gnokey` directory.

The same error presents when trying to sign with the key.

### PR DESCRIPTION
**Pull request by jefft0**
Resolves #2737

As [required by the HID library](https://github.com/Zondax/hid/blob/148be243caa49724e017c248dde643b0ada03742/README.md?plain=1#L31), the executable must be built with `CGO_ENABLED=1` in order to find the Ledger. We want to keep building without this flag by default so that the binary is deterministic. The HID library already has the [`Supported` function](https://github.com/Zondax/hid/blob/148be243caa49724e017c248dde643b0ada03742/hid_disabled.go#L15) which returns false if not built with cgo.

* In the `getLedgerDevice`, if not `Supported` then return an error message to try building with CGO_ENABLED=1

The error message looks like:
```
unable to create Ledger reference in keybase, ledger support is not enabled, try building with CGO_ENABLED=1
```

This PR is a minimal solution as an alternative to putting `CGO_ENABLED=1` in the [gnokey Makefile](https://github.com/gnolang/gno/blob/e3df2c9e0bb17ddc90f34db223ab6593b4f6ca8a/gno.land/Makefile#L48).

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
 🟢 Pending initial approval by a review team member, or review from tech-staff


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: jefft0/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

<details><summary>Pending initial approval by a review team member, or review from tech-staff</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 Not (🔴 Pull request author is a member of the team: tech-staff)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 If
    ├── 🟢 Condition
    │   └── 🟢 Or
    │       ├── 🔴 At least one of these user(s) reviewed the pull request: [jefft0 leohhhn n0izn0iz notJoon omarsy x1unix] (with state "APPROVED")
    │       ├── 🟢 At least 1 user(s) of the team tech-staff reviewed pull request
    │       └── 🔴 This pull request is a draft
    └── 🟢 Then
        └── 🟢 Not (🔴 This label is applied to pull request: review/triage-pending)

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

**Review by zivkovicmilos — APPROVED** [review]

File: tm2/pkg/crypto/ledger/ledger_secp256k1.go [hunk 1]
```diff
@@ -177,6 +178,10 @@ func convertDERtoBER(signatureDER []byte) ([]byte, error) {
 }
 
 func getLedgerDevice() (ledger.SECP256K1, error) {
+	if !hid.Supported() {
+		return nil, fmt.Errorf("Ledger support is not enabled. Try building with CGO_ENABLED=1")
```
Comment (aeddi) [inline tm2/pkg/crypto/ledger/ledger_secp256k1.go]:
```suggestion
		return nil, fmt.Errorf("ledger support is not enabled, try building with CGO_ENABLED=1")
```

(Error strings should not be capitalized)

**Review by aeddi — APPROVED** [review]
