### PR TITLE
fix(vm): Release VM properly

### LINKED ISSUE #1033: VM is not properly released back to sync pool
This will not zero the m.Ops and m.Values slice. 

_Originally posted by @piux2 in https://github.com/gnolang/gno/issues/894#issuecomment-1668876811_

The opZeroed and valueZeroed arrays are fixed in size with a length of 1024. However, m.Ops and m.Values are slices, and their length could far exceed 1024. The copy() function, in this context, only zeroes out the first 1024 elements of the slice, leaving the remainder unchanged.

Here's a sample code that illustrates this behavior:
https://go.dev/play/p/JoShYG2Q8lf

Given the above, I don't see a significant advantage to zeroing out the entire slice. 
A more effective approach might be to set the slice to nil, allowing the Go runtime to garbage collect the underlying arrays.

Here's why:

The VM machine operates within a transactional context, with its lifecycle managed by this context. The efficiency of interactions with gno.land is governed by the time it takes to process requests and responses within this context. The Go runtime handles the allocation and management of underlying slice memory far better than the manual methods we're attempting here.

Furthermore, there's an oversight: only m.Ops and m.Values are being considered for reset. The machine also retains m.Exprs, m.Stmts, m.Blocks, and m.Frames, all of which are slices. It's crucial to release these as well.

### PR DESCRIPTION
**Pull request by ajnavarro**
Properly clean slices using make (the internal logic is expecting slices to not be nil).

It closes #1033

- [X] Added new tests, or not needed, or not feasible
- [X] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [X] Updated the official documentation or not needed
- [X] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [X] Added references to related issues and PRs
- [X] Provided any useful hints for running manual tests
- [X] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).

### CODE REVIEW

**Review by zivkovicmilos — APPROVED** [review]

File: gnovm/pkg/gnolang/machine.go [hunk 1]
```diff
@@ -154,13 +148,16 @@ var (
...
-	// this is the fastest way to zero-in a slice in Go
-	copy(m.Ops, opZeroed[:])
-	copy(m.Values, valueZeroed[:])
+
+	m.Ops = make([]Op, VMSliceSize)
+	m.Values = make([]TypedValue, VMSliceSize)
+	m.Exprs = nil
+	m.Stmts = nil
+	m.Blocks = nil
+	m.Frames = nil
```
Comment (thehowl) [inline gnovm/pkg/gnolang/machine.go:160]: What if instead we did this?

```suggestion
	ops, values := m.Ops[:VMSliceSize:VMSliceSize], m.Values[:VMSliceSize:VMSliceSize]
	copy(ops, opZeroed[:])
	copy(values, valueZeroed[:])
	*m = Machine{Ops: ops, Values: values} 
```

This way we zero-in all other values, while also resetting correctly without reallocating Ops and Values. The remaining part of both slices (exceeding `VMSliceSize`) is outside of the cap, and can be safely collected by the gc...

Calling `make` here makes the whole machinePool shenanigans more useless than it currently is.

Consequently, could update `NewMachineWithOptions` by making it get the machine from the pool and then only changing the fields it needs to change.

(I think @piux2 missed that part of the code, which is probably the whole reason why the gnovm kept working nonetheless. Although not zeroing in everything else in this fn probably lead to memory leaks).

**Comment by ajnavarro** [comment]
@thehowl  Applied requested changes and added benchmarks:

```
PR with makes:
BenchmarkCreateNewMachine-12    	  160599	     13276 ns/op	   45496 B/op	      35 allocs/op

Master branch:
BenchmarkCreateNewMachine-12    	  317624	      7059 ns/op	    3243 B/op	      32 allocs/op

Add changes to the release method:
BenchmarkCreateNewMachine-12    	  318438	      7214 ns/op	    3246 B/op	      32 allocs/op

Add changes to the NewMachineWithOptions method:
BenchmarkCreateNewMachine-12    	  323756	      7193 ns/op	    3240 B/op	      32 allocs/op
```

**Review by moul — APPROVED** [review]

**Review by thehowl — APPROVED** [review]
